// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id: info.h,v 1.7 2001/08/07 00:53:33 hurdler Exp $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Portions Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// $Log: info.h,v $
// Revision 1.7  2001/08/07 00:53:33  hurdler
// lil' change
//
// Revision 1.6  2001/01/25 22:15:42  bpereira
// added heretic support
//
// Revision 1.5  2000/11/02 17:50:07  stroggonmeth
// Big 3Dfloors & FraggleScript commit!!
//
// Revision 1.4  2000/10/21 08:43:29  bpereira
// no message
//
// Revision 1.3  2000/04/04 00:32:46  stroggonmeth
// Initial Boom compatability plus few misc changes all around.
//
// Revision 1.2  2000/02/27 00:42:10  hurdler
// fix CR+LF problem
//
// Revision 1.1.1.1  2000/02/22 20:32:32  hurdler
// Initial import into CVS (v1.29 pr3)
//
//
// DESCRIPTION:
//      Thing frame/state LUT,
//      generated by multigen utilitiy.
//      This one is the original DOOM version, preserved.
//
//-----------------------------------------------------------------------------

#ifndef __INFO__
#define __INFO__

// Needed for action function pointer handling.
#include "d_think.h"

typedef enum
{
    SPR_MISL,
    SPR_PLAY,
    SPR_POSS,
    SPR_SPOS,
    SPR_EGGM,
    SPR_BON1,
    SPR_SRBX,
    SPR_GRBX,
    SPR_EMMY, // emerald test tails
    SPR_PINV,
    SPR_GRTV, // Tails 9-30-99
    SPR_SPRY,
	SPR_SUDY,
    SPR_SHTV, // Tails 9-30-99
    SPR_FANS,
    SPR_BUBL, // water bubble source Tails 03-07-2000
    SPR_BLTV, // Tails 9-30-99
    SPR_YLTV, // Tails 9-30-99
    SPR_FWR1,
    SPR_SPRR,
	SPR_SUDR,
    //Fab:
    SPR_SMOK,
    SPR_SPLA,
    SPR_TNT1, //SoM: 3/8/2000: add invisible sprite
	SPR_BIRD, // Tails 10-20-99 Birdie freed!
    SPR_SQRL, // Tails 10-20-99 Squirrel freed!
    SPR_BORB, // Tails 12-29-99 Blue Shield
    SPR_YORB, // Tails 12-29-99 Yellow Shield
    SPR_GORB, // Tails 12-29-99 Green Shield
    SPR_KORB, // Tails 12-29-99 Black Shield
    SPR_SPRK, // spark tails
    SPR_IVSP, // invincibility sparkles tails
    SPR_IVSQ, // finish invincibility sparkles tails
    SPR_DISS, // dissipating object tails
    SPR_BUBP, // Small bubble Tails 03-07-2000
    SPR_BUBO, // Medium bubble Tails 03-07-2000
    SPR_BUBN, // Large bubble Tails 03-07-2000
    SPR_BUBM, // Extra Large (would you like fries with that?) bubble Tails 03-07-2000
    SPR_CNTA, // Drowning Timer - 0 Tails 03-07-2000
    SPR_CNTB, // Drowning Timer - 1 Tails 03-07-2000
    SPR_CNTC, // Drowning Timer - 2 Tails 03-07-2000
    SPR_CNTD, // Drowning Timer - 3 Tails 03-07-2000
    SPR_CNTE, // Drowning Timer - 4 Tails 03-07-2000
    SPR_CNTF, // Drowning Timer - 5 Tails 03-07-2000
    SPR_POPP, // Extra Large bubble goes POP! Tails 03-08-2000
    SPR_PRUP, // 1up Box Tails 03-12-2000
    SPR_BKTV, // Black shield TV Tails 04-08-2000
    SPR_SCRA, // 100 score logo Tails 04-16-2000
    SPR_SCRB, // 200 score logo Tails 04-16-2000
    SPR_SCRC, // 500 score logo Tails 04-16-2000
    SPR_SCRD, // 1000 score logo Tails 04-16-2000
    SPR_SSPK, // Super Sonic Spark Tails 04-18-2000
    SPR_GRAS, // Grass debris Tails 05-14-2000
    SPR_YSPR, // Yellow Diagonal Spring Tails 05-17-2000
	SPR_RSPR, // Red Diagonal Spring Tails 05-27-2003
	SPR_YSUD, // Yellow Upside-Down Diagonal Spring 05-27-2003
	SPR_RSUD, // Red Upside-Down Diagonal Spring 05-27-2003
    SPR_SKIM, // Skim mine dropper Tails 06-13-2000
    SPR_MINE, // Skim mine Tails 06-13-2000
    SPR_FISH, // Greenflower Fish Tails 07-03-2000
    SPR_GARG, // Deep Sea Gargoyle Tails 07-29-2000
	SPR_SPLH, // Tails 12-08-2000
    SPR_THOK, // Tails 12-05-99 Thok! mobj
	SPR_THZP, // Techno Hill Zone Plant Tails 12-19-2000
	SPR_SIGN, // Level end sign Tails 01-14-2001
	SPR_RRNG, // Red Ring Tails 03-13-2001
	SPR_TTAG, // Tag Sign Tails 05-08-2001
	SPR_STEM, // Steam riser Tails 05-28-2001
	SPR_RFLG, // Red CTF Flag Tails 07-22-2001
	SPR_BFLG, // Blue CTF Flag Tails 07-22-2001
	SPR_GFLG, // Got Flag sign Tails 07-22-2001
	SPR_TOKE, // Special Stage Token Tails 08-11-2001
	SPR_CEMG, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMO, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMP, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMB, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMR, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEML, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMY, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_JETB, // Jetty-Syn Bomber Tails 08-18-2001
	SPR_JETG, // Jetty-Syn Gunner Tails 08-25-2001
	SPR_JBUL, // Jetty-Syn Bullet Tails 08-25-2001
	SPR_MOUS, // Mouse Tails 08-26-2001
	SPR_DETN, // Deton Tails 08-26-2001
	SPR_XPLD, // Robot Explosion Tails 08-26-2001
	SPR_CHAN, // CEZ Chain Tails 11-02-2001
	SPR_CAPE, // Fake little Super Sonic cape Tails 11-12-2001
	SPR_SNO1, // Snowflake Tails 12-02-2001
	SPR_SANT, // Santa Tails 12-12-2001
	SPR_EMER, // Emerald Hunt 1 Tails 12-12-2001
	SPR_EMES, // Emerald Hunt 2 Tails 12-12-2001
	SPR_EMET, // Emerald Hunt 3 Tails 12-12-2001
	SPR_SBLL, // Snow Ball for Snow Buster Tails 12-12-2001
	SPR_SPIK, // Spike Ball Tails 12-18-2001
	SPR_CCOM, // Crawla Commander Tails 12-30-2001
	SPR_RAIN, // Rain Tails 06-07-2002
	SPR_DSPK, // Ceiling spike Tails 06-15-2002
	SPR_USPK, // Floor spike Tails 06-15-2002
	SPR_STPT, // Starpost Tails 07-03-2002
	SPR_RNGM, // Homing Ring
	SPR_RNGR, // Rail Ring
	SPR_RNGS, // Shield Ring
	SPR_RNGA, // Automatic Ring
	SPR_RNGE, // Explosion Ring
	SPR_TAEH, // Thrown Automatic Explosion Homing ring
	SPR_TAER, // Thrown Automatic Explosion Ring
	SPR_THER, // Thrown Homing Explosion Ring
	SPR_TAHR, // Thrown Automatic Homing Ring
	SPR_THOM, // Thrown Homing Ring
	SPR_TAUT, // Thrown Automatic Ring
	SPR_TEXP, // Thrown Explosion Ring
	SPR_BUS1, // GFZ Bush w/ berries
	SPR_BUS2, // GFZ Bush w/o berries
	SPR_FWR2, // GFZ Sunflower
	SPR_FWR3, // GFZ budding flower
	SPR_MIXU, // Player mixing monitor Tails 08-28-2002
	SPR_QUES, // Random monitor Tails 08-28-2002
	SPR_MTEX, // Exploding monitor Tails 08-28-2002
	SPR_FLAM, // Flame (has corona) Tails 09-06-2002
	SPR_LASR, // THZ Laser Tails 09-23-2002

	// Mario-specific stuff Tails 09-10-2002
	SPR_PUMA,
	SPR_HAMM,
	SPR_KOOP,
	SPR_SHLL,
	SPR_MAXE,
	SPR_BFLM,
	SPR_FBLL,
	SPR_FFWR,

	SPR_NSPK, // NiGHTS sparkle
	SPR_SUPE, // NiGHTS character flying
	SPR_SUPZ, // NiGHTS hurt
	SPR_NDRN, // NiGHTS drone
	SPR_NDRL, // NiGHTS character drilling

	SPR_SEED, // Sonic CD flower seed
	SPR_JETF, // Boss jet fumes
	SPR_HOOP, // NiGHTS hoop sprite
	SPR_NSCR, // NiGHTS score sprite
	SPR_NWNG, // NiGHTS Wing collectable item.
	SPR_EGGN, // Boss 2
	SPR_GOOP, // Boss 2 Goop
	SPR_BPLD, // Boss Explosions
	SPR_ALRM, // THZ2 Alarm

	SPR_RDTV, // Red shield Tails 12-18-2002
	SPR_RORB, // Red orb Tails 12-18-2002

	SPR_EGGB, // Eggman box Tails 12-19-2002
	SPR_SFLM, // Spin fire Tails 12-19-2002

	SPR_TNKA, // Boss 2 Tank 1
	SPR_TNKB, // Boss 2 Tank 2
	SPR_SPNK, // Boss 2 Spigot

	SPR_TFOG, // Teleport Fog Tails 01-12-2003
	SPR_EEGG, // Easter Egg!

	SPR_LITE, // Streetlight corona Tails 02-18-2003
	SPR_TRET,
	SPR_TRLS,
	SPR_FWR4,

	SPR_GOOM,
	SPR_BGOM,
	SPR_MUS1,
	SPR_MUS2,
	SPR_TOAD,
	SPR_COIN,
	SPR_CPRK,

	SPR_XMS1,
	SPR_XMS2,
	SPR_XMS3,

	SPR_CAPS, // Capsule thingy for NiGHTS

	SPR_SUPT, // Super Sonic Transformation

	SPR_ROID, // Crumbly rock

	// NiGHTS Paraloop Powerups Tails 12-15-2003
	SPR_NPRA,
	SPR_NPRB,
	SPR_NPRC,

	SPR_REDX, // He's BACK!

    NUMSPRITES

} spritenum_t;

typedef enum
{
    S_NULL,
    S_ROCKET,
    S_PLAY_STND,
    S_PLAY_TAP1, // Tails 12-03-99
    S_PLAY_TAP2, // Tails 12-03-99
    S_PLAY_RUN1,
    S_PLAY_RUN2,
    S_PLAY_RUN3,
    S_PLAY_RUN4,
    S_PLAY_RUN5, // Tails 9-14-99
    S_PLAY_RUN6, // Tails 9-14-99
    S_PLAY_RUN7, // Tails 9-14-99
    S_PLAY_RUN8, // Tails 9-14-99
    S_PLAY_ATK1, // Tails 9-14-99
    S_PLAY_ATK2, // Tails 9-14-99
    S_PLAY_ATK3, // Tails 9-14-99
    S_PLAY_ATK4, // Tails 9-14-99
    S_PLAY_PLG1, // Tails 9-14-99
    S_PLAY_SPD1, // Tails 03-02-2000
    S_PLAY_SPD2, // Tails 03-02-2000
    S_PLAY_SPD3, // Tails 03-02-2000
    S_PLAY_SPD4, // Tails 03-02-2000
    S_PLAY_ABL1, // Tails 03-02-2000
    S_PLAY_ABL2, // Tails 03-02-2000
    S_PLAY_SPC1, // Tails 03-02-2000
    S_PLAY_SPC2, // Tails 03-02-2000 ---- Finalized the character spec
    S_PLAY_SPC3, // Tails 03-02-2000
    S_PLAY_SPC4, // Tails 03-02-2000
	S_PLAY_CLIMB1, // Tails 01-03-2001
	S_PLAY_CLIMB2, // Tails 01-03-2001
	S_PLAY_CLIMB3, // Tails 01-03-2001
	S_PLAY_CLIMB4, // Tails 01-03-2001
	S_PLAY_CLIMB5, // Tails 01-03-2001
    S_PLAY_GASP, // Tails 03-02-2000
    S_PLAY_PAIN, // Tails 03-02-2000
    S_PLAY_DIE1, // Tails 03-02-2000
    S_PLAY_DIE2, // Tails 03-02-2000
    S_PLAY_DIE3, // Tails 03-02-2000
    S_PLAY_TEETER1, // Tails 03-02-2000
    S_PLAY_TEETER2, // Tails 03-02-2000
	S_PLAY_FALL1, // Tails 03-02-2000
	S_PLAY_FALL2, // Tails 03-02-2000
	S_PLAY_CARRY,
// New Crawla Animations Tails 06-13-2000
    S_POSS_STND,
    S_POSS_STND2,
    S_POSS_RUN1,
    S_POSS_RUN2,
    S_POSS_RUN3,
    S_POSS_RUN4,
    S_POSS_RUN5,
    S_POSS_RUN6,
    S_POSS_RUN7,
    S_POSS_RUN8,
    S_POSS_RUN9,
    S_POSS_RUN10,
    S_POSS_RUN11,
    S_POSS_RUN12,
    S_POSS_RUN13,
    S_POSS_RUN14,
    S_POSS_RUN15,
    S_POSS_RUN16,
    S_POSS_RUN17,
	S_POSS_DIE1,
	S_POSS_DIE2,
	S_POSS_DIE3,
	S_POSS_DIE4,
// XDIE frames deleted Tails 10-25-99
// New Crawla Animations Tails 06-13-2000
    S_SPOS_STND,
    S_SPOS_STND2,
    S_SPOS_RUN1,
    S_SPOS_RUN2,
    S_SPOS_RUN3,
    S_SPOS_RUN4,
    S_SPOS_RUN5,
    S_SPOS_RUN6,
    S_SPOS_RUN7,
    S_SPOS_RUN8,
    S_SPOS_RUN9,
    S_SPOS_RUN10,
    S_SPOS_RUN11,
    S_SPOS_RUN12,
    S_SPOS_RUN13,
    S_SPOS_RUN14,
    S_SPOS_RUN15,
    S_SPOS_RUN16,
    S_SPOS_RUN17,
	S_SPOS_DIE1,
	S_SPOS_DIE2,
	S_SPOS_DIE3,
	S_SPOS_DIE4,
// XDIE frames deleted Tails 10-25-99
    S_EGGMOBILE_STND, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PANIC1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PANIC2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE13, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE14, // Boss 1 Tails 11-29-99
	S_EGGMOBILE_FLEE1,
	S_EGGMOBILE_FLEE2,
    S_BON1,
    S_BON1A,
    S_BON1B,
    S_BON1C,
    S_BON1D,
    S_BON1E,
    S_BON1F, //Tails 9-15-99
    S_BON1G, //Tails 9-15-99
    S_BON1H, //Tails 9-15-99
    S_BON1I, //Tails 9-15-99
    S_BON1J, //Tails 9-15-99
    S_BON1K, //Tails 9-15-99
    S_BON1L, //Tails 9-15-99
    S_BON1M, //Tails 9-15-99
    S_BON1N, //Tails 9-15-99
    S_BON1O,  //Tails 9-15-99
    S_BON1P,  //Tails 10-29-99
    S_BON1Q,  //Tails 10-29-99
    S_BON1R,  //Tails 10-29-99
    S_BON1S,  //Tails 10-29-99
    S_BON1T,  //Tails 10-29-99
    S_BON1U,  //Tails 10-29-99
    S_BON1V,  //Tails 10-29-99
    S_BON1W,  //Tails 10-29-99
    S_SUPERRINGBOX,
    S_SUPERRINGBOX1, // Tails 9-30-99
    S_SUPERRINGBOX2, // Tails 9-30-99
    S_SUPERRINGBOX3, // Tails 9-30-99
    S_GREYRINGBOX,
    S_GREYRINGBOX1, // Tails 9-30-99
    S_GREYRINGBOX2, // Tails 9-30-99
    S_GREYRINGBOX3, // Tails 9-30-99
    S_EMMY1, // start emerald tails
    S_EMMY2,
    S_EMMY3,
    S_EMMY4,
    S_EMMY5,
    S_EMMY6,
    S_EMMY7, // end emerald tails
    S_PINV, // start invincibility box tails
    S_PINV2,
    S_PINV3,
    S_PINV4,
    S_GRTV, // Tails 9-30-99
    S_GRTV1, // Tails 9-30-99
    S_GRTV2, // Tails 9-30-99
    S_GRTV3, // Tails 9-30-99
    S_YELLOWSPRING,
    S_YELLOWSPRING2, // Tails 11-06-99
    S_YELLOWSPRING3, // Tails 11-06-99
    S_YELLOWSPRING4, // Tails 11-06-99
    S_YELLOWSPRING5, // Tails 11-06-99
    S_YELLOWSPRINGUD,
    S_YELLOWSPRINGUD2, // Tails 05-27-2003
    S_YELLOWSPRINGUD3, // Tails 05-27-2003
    S_YELLOWSPRINGUD4, // Tails 05-27-2003
    S_YELLOWSPRINGUD5, // Tails 05-27-2003
    S_SHTV, // Tails 9-30-99
    S_SHTV1, // Tails 9-30-99
    S_SHTV2, // Tails 9-30-99
    S_SHTV3, // Tails 9-30-99
    S_FAN, // It's da fan! Tails 12-05-99
    S_FAN2, // It's da fan! Tails 12-05-99
    S_FAN3, // It's da fan! Tails 12-05-99
    S_FAN4, // It's da fan! Tails 12-05-99
    S_FAN5, // It's da fan! Tails 12-05-99
    S_BUBBLES1, // Bubble Source Tails 03-07-2000
    S_BUBBLES2, // Bubble Source Tails 03-07-2000
    S_BLTV, // Tails 9-30-99
    S_BLTV1, // Tails 9-30-99
    S_BLTV2, // Tails 9-30-99
    S_BLTV3, // Tails 9-30-99
    S_YLTV, // Tails 9-30-99
    S_YLTV1, // Tails 9-30-99
    S_YLTV2, // Tails 9-30-99
    S_YLTV3, // Tails 9-30-99
    S_GFZFLOWERA,
    S_GFZFLOWERA2,
    S_REDSPRING,
    S_REDSPRING2, // Tails 11-07-99
    S_REDSPRING3, // Tails 11-07-99
    S_REDSPRING4, // Tails 11-07-99
    S_REDSPRING5, // Tails 11-07-99
    S_REDSPRINGUD,
    S_REDSPRINGUD2, // Tails 05-27-2003
    S_REDSPRINGUD3, // Tails 05-27-2003
    S_REDSPRINGUD4, // Tails 05-27-2003
    S_REDSPRINGUD5, // Tails 05-27-2003
    //Fab: added lava/slime damage burn smoke
    S_SMOK1,
    S_SMOK2,
    S_SMOK3,
    S_SMOK4,
    S_SMOK5,
    //Fab: added water splash
    S_SPLASH1,
    S_SPLASH2,
    S_SPLASH3,
    S_TNT1,   //SoM: 3/9/2000: add state for invisible sprite
	S_BIRD1, // Tails 10-20-99 Birdie free!
    S_BIRD2, // Tails 10-20-99 Birdie free!
    S_BIRD3, // Tails 10-23-99 Birdie free!
    S_SQRL1, // Tails 10-20-99 Squirrel free!
    S_SQRL2, // Tails 10-20-99 Squirrel free!
    S_SQRL3, // Tails 10-23-99 Squirrel free!
    S_SQRL4, // Tails 10-20-99 Squirrel free!
    S_SQRL5, // Tails 10-20-99 Squirrel free!
    S_SQRL6, // Tails 10-20-99 Squirrel free!
    S_SQRL7, // Tails 10-20-99 Squirrel free!
    S_SQRL8, // Tails 10-20-99 Squirrel free!
    S_SQRL9, // Tails 10-20-99 Squirrel free!
    S_SQRL10, // Tails 10-20-99 Squirrel free!
    S_BORB1, // Tails 12-29-99 shield mobjs
    S_BORB2, // Tails 12-29-99 shield mobjs
    S_BORB3, // Tails 12-29-99 shield mobjs
    S_BORB4, // Tails 12-29-99 shield mobjs
    S_BORB5, // Tails 12-29-99 shield mobjs
    S_BORB6, // Tails 12-29-99 shield mobjs
    S_BORB7, // Tails 12-29-99 shield mobjs
    S_BORB8, // Tails 12-29-99 shield mobjs
    S_YORB1, // Tails 12-29-99 shield mobjs
    S_YORB2, // Tails 12-29-99 shield mobjs
    S_YORB3, // Tails 12-29-99 shield mobjs
    S_YORB4, // Tails 12-29-99 shield mobjs
    S_YORB5, // Tails 12-29-99 shield mobjs
    S_YORB6, // Tails 12-29-99 shield mobjs
    S_YORB7, // Tails 12-29-99 shield mobjs
    S_YORB8, // Tails 12-29-99 shield mobjs
    S_GORB1, // Tails 12-29-99 shield mobjs
    S_GORB2, // Tails 06-28-2000 shield mobjs
    S_GORB3, // Tails 06-28-2000 shield mobjs
    S_GORB4, // Tails 06-28-2000 shield mobjs
    S_GORB5, // Tails 06-28-2000 shield mobjs
    S_GORB6, // Tails 06-28-2000 shield mobjs
    S_GORB7, // Tails 06-28-2000 shield mobjs
    S_GORB8, // Tails 06-28-2000 shield mobjs
    S_KORB1, // Tails 12-29-99 shield mobjs
    S_KORB2, // Tails 12-29-99 shield mobjs
    S_KORB3, // Tails 12-29-99 shield mobjs
    S_KORB4, // Tails 12-29-99 shield mobjs
    S_KORB5, // Tails 12-29-99 shield mobjs
    S_KORB6, // Tails 12-29-99 shield mobjs
    S_KORB7, // Tails 12-29-99 shield mobjs
    S_KORB8, // Tails 12-29-99 shield mobjs
    S_RORB1, // Tails 12-18-2002 shield mobjs
    S_RORB2, // Tails 12-18-2002 shield mobjs
    S_RORB3, // Tails 12-18-2002 shield mobjs
    S_RORB4, // Tails 12-18-2002 shield mobjs
    S_RORB5, // Tails 12-18-2002 shield mobjs
    S_RORB6, // Tails 12-18-2002 shield mobjs
    S_RORB7, // Tails 12-18-2002 shield mobjs
    S_RORB8, // Tails 12-18-2002 shield mobjs
    S_SPRK1, // spark start tails
    S_SPRK2,
    S_SPRK3,
    S_SPRK4,
    S_SPRK5, // spark
    S_SPRK6,
    S_SPRK7,
    S_SPRK8,
    S_SPRK9, // spark
    S_SPRK10,
    S_SPRK11,
    S_SPRK12,
    S_SPRK13, // spark
    S_SPRK14,
    S_SPRK15,
    S_SPRK16, // end spark tails
    S_IVSP1, // invincibility sparkles tails
    S_IVSP2, // invincibility sparkles tails
    S_IVSP3, // invincibility sparkles tails
    S_IVSP4, // invincibility sparkles tails
    S_IVSP5, // invincibility sparkles tails
    S_IVSP6, // invincibility sparkles tails
    S_IVSP7, // invincibility sparkles tails
    S_IVSP8, // invincibility sparkles tails
    S_IVSP9, // invincibility sparkles tails
    S_IVSP10, // invincibility sparkles tails
    S_IVSP11, // invincibility sparkles tails
    S_IVSP12, // invincibility sparkles tails
    S_IVSP13, // invincibility sparkles tails
    S_IVSP14, // invincibility sparkles tails
    S_IVSP15, // invincibility sparkles tails
    S_IVSP16, // invincibility sparkles tails
    S_IVSP17, // invincibility sparkles tails
    S_IVSP18, // invincibility sparkles tails
    S_IVSP19, // invincibility sparkles tails
    S_IVSP20, // invincibility sparkles tails
    S_IVSP21, // invincibility sparkles tails
    S_IVSP22, // invincibility sparkles tails
    S_IVSP23, // invincibility sparkles tails
    S_IVSP24, // invincibility sparkles tails
    S_IVSP25, // invincibility sparkles tails
    S_IVSP26, // invincibility sparkles tails
    S_IVSP27, // invincibility sparkles tails
    S_IVSP28, // invincibility sparkles tails
    S_IVSP29, // invincibility sparkles tails
    S_IVSQ1, // invincibility sparkles finish tails
    S_IVSQ2, // invincibility sparkles finish tails
    S_IVSQ3, // invincibility sparkles finish tails
    S_DISS, // dissipating object tails
    S_SMALLBUBBLE, // small bubble Tails 03-07-2000
    S_SMALLBUBBLE1, // small bubble Tails 03-07-2000
    S_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
    S_MEDIUMBUBBLE1, // medium bubble Tails 03-07-2000
    S_LARGEBUBBLE, // large bubble Tails 03-07-2000
    S_EXTRALARGEBUBBLE, // extra large bubble (breathable) Tails 03-07-2000
    S_EXTRALARGEBUBBLE1, // extra large bubble (breathable) Tails 03-07-2000
    S_ZERO1, // Drowning Timer - 0 Tails 03-07-2000
    S_ONE1, // Drowning Timer - 1 Tails 03-07-2000
    S_TWO1, // Drowning Timer - 2 Tails 03-07-2000
    S_THREE1, // Drowning Timer - 3 Tails 03-07-2000
    S_FOUR1, // Drowning Timer - 4 Tails 03-07-2000
    S_FIVE1, // Drowning Timer - 5 Tails 03-07-2000
    S_POP1, // Extra Large bubble goes POP! Tails 03-08-2000
    S_PRUP1, // 1Up box Tails 03-12-2000
    S_PRUP2, // 1Up box Tails 03-12-2000
    S_PRUP3, // 1Up box Tails 03-12-2000
    S_PRUP4, // 1Up box Tails 03-12-2000
    S_BKTV1, // Black shield TV Tails 04-08-2000
    S_BKTV2, // Black shield TV Tails 04-08-2000
    S_BKTV3, // Black shield TV Tails 04-08-2000
    S_BKTV4, // Black shield TV Tails 04-08-2000
	S_RDTV1, // Tails 12-18-2002
	S_RDTV2, // Tails 12-18-2002
	S_RDTV3, // Tails 12-18-2002
	S_RDTV4, // Tails 12-18-2002
    S_SCRA, // 100 score logo Tails 04-16-2000
    S_SCRA2, // 100 score logo Tails 04-16-2000
    S_SCRB, // 200 score logo Tails 04-16-2000
    S_SCRB2, // 200 score logo Tails 04-16-2000
    S_SCRC, // 500 score logo Tails 04-16-2000
    S_SCRC2, // 500 score logo Tails 04-16-2000
    S_SCRD, // 1000 score logo Tails 04-16-2000
    S_SCRD2, // 1000 score logo Tails 04-16-2000
    S_SSPK1, // Super Sonic Spark Tails 04-18-2000
    S_SSPK2, // Super Sonic Spark Tails 04-18-2000
    S_SSPK3, // Super Sonic Spark Tails 04-18-2000
    S_SSPK4, // Super Sonic Spark Tails 04-18-2000
    S_SSPK5, // Super Sonic Spark Tails 04-18-2000
    S_GRASS1, // Grass debris Tails 05-14-2000
    S_GRASS2, // Grass debris Tails 05-14-2000
    S_GRASS3, // Grass debris Tails 05-14-2000
    S_GRASS4, // Grass debris Tails 05-14-2000
    S_GRASS5, // Grass debris Tails 05-14-2000
    S_GRASS6, // Grass debris Tails 05-14-2000
    S_GRASS7, // Grass debris Tails 05-14-2000
    S_YDIAG1, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG2, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG3, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG4, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG5, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG6, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG7, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG8, // Yellow Diagonal Spring Tails 05-17-2000
    S_RDIAG1, // Red Diagonal Spring Tails 05-17-2000
    S_RDIAG2, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG3, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG4, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG5, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG6, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG7, // Red Diagonal Spring Tails 05-27-2003
    S_RDIAG8, // Red Diagonal Spring Tails 05-27-2003
    S_YDIAGD1, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD2, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD3, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD4, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD5, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD6, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD7, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_YDIAGD8, // Yellow Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD1, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD2, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD3, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD4, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD5, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD6, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD7, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_RDIAGD8, // Red Upside-Down Diagonal Spring Tails 05-27-2003
    S_SKIM1, // Skim mine dropper Tails 06-13-2000
    S_SKIM2, // Skim mine dropper Tails 06-13-2000
    S_SKIM3, // Skim mine dropper Tails 06-13-2000
    S_SKIM4, // Skim mine dropper Tails 06-13-2000
    S_SKIM5, // Skim mine dropper Tails 06-13-2000
    S_SKIM6, // Skim mine dropper Tails 06-13-2000
    S_SKIM7, // Skim mine dropper Tails 06-13-2000
    S_SKIM8, // Skim mine dropper Tails 06-13-2000
    S_SKIM9, // Skim mine dropper Tails 06-13-2000
    S_SKIM10, // Skim mine dropper Tails 06-13-2000
    S_SKIM11, // Skim mine dropper Tails 06-13-2000
    S_SKIM12, // Skim mine dropper Tails 06-13-2000
    S_SKIM13, // Skim mine dropper Tails 06-13-2000
    S_SKIM14, // Skim mine dropper Tails 06-13-2000
    S_SKIM15, // Skim mine dropper Tails 06-13-2000
    S_SKIM16, // Skim mine dropper Tails 06-13-2000
    S_SKIM17, // Skim mine dropper Tails 06-13-2000
    S_SKIM18, // Skim mine dropper Tails 06-13-2000
    S_SKIM19, // Skim mine dropper Tails 06-13-2000
    S_SKIM20, // Skim mine dropper Tails 06-13-2000
    S_SKIM21, // Skim mine dropper Tails 06-13-2000
    S_SKIM22, // Skim mine dropper Tails 06-13-2000
    S_SKIM23, // Skim mine dropper Tails 06-13-2000
    S_SKIM24, // Skim mine dropper Tails 06-13-2000
    S_SKIM25, // Skim mine dropper Tails 06-13-2000
    S_SKIM26, // Skim mine dropper Tails 06-13-2000
    S_SKIM27, // Skim mine dropper Tails 06-13-2000
    S_SKIM28, // Skim mine dropper Tails 06-13-2000
    S_SKIM29, // Skim mine dropper Tails 06-13-2000
    S_SKIM30, // Skim mine dropper Tails 06-13-2000
    S_SKIM_BOOM1, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM2, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM3, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM4, // Skim mine dropper explode Tails 06-13-2000
    S_MINE1, // Skim mine Tails 06-13-2000
    S_MINE_BOOM1, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM2, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM3, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM4, // Skim mine explode Tails 06-13-2000
    S_FISH1, // Greenflower Fish Tails 07-03-2000
    S_FISH2, // Greenflower Fish Tails 07-03-2000
    S_FISH3, // Greenflower Fish Tails 07-03-2000
    S_FISH4, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE1, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE2, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE3, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE4, // Greenflower Fish Tails 07-03-2000
    S_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	S_SPLISH1, // Tails 12-08-2000
	S_SPLISH2, // Tails 12-08-2000
	S_SPLISH3, // Tails 12-08-2000
	S_SPLISH4, // Tails 12-08-2000
	S_SPLISH5, // Tails 12-08-2000
	S_SPLISH6, // Tails 12-08-2000
	S_SPLISH7, // Tails 12-08-2000
	S_SPLISH8, // Tails 12-08-2000
	S_SPLISH9, // Tails 12-08-2000
    S_THOK1, // Tails 12-05-99 Thok! mobj
	S_THZPLANT1, // THZ Plant Tails 12-19-2000
	S_THZPLANT2, // THZ Plant Tails 12-19-2000
	S_THZPLANT3, // THZ Plant Tails 12-19-2000
	S_THZPLANT4, // THZ Plant Tails 12-19-2000
	S_SIGN1, // Level end sign Tails 01-14-2001
	S_SIGN2, // Level end sign Tails 01-14-2001
	S_SIGN3, // Level end sign Tails 01-14-2001
	S_SIGN4, // Level end sign Tails 01-14-2001
	S_SIGN5, // Level end sign Tails 01-14-2001
	S_SIGN6, // Level end sign Tails 01-14-2001
	S_SIGN7, // Level end sign Tails 01-14-2001
	S_SIGN8, // Level end sign Tails 01-14-2001
	S_SIGN9, // Level end sign Tails 01-14-2001
	S_SIGN10, // Level end sign Tails 01-14-2001
	S_SIGN11, // Level end sign Tails 01-14-2001
	S_SIGN12, // Level end sign Tails 01-14-2001
	S_SIGN13, // Level end sign Tails 01-14-2001
	S_SIGN14, // Level end sign Tails 01-14-2001
	S_SIGN15, // Level end sign Tails 01-14-2001
	S_SIGN16, // Level end sign Tails 01-14-2001
	S_SIGN17, // Level end sign Tails 01-14-2001
	S_SIGN18, // Level end sign Tails 01-14-2001
	S_SIGN19, // Level end sign Tails 01-14-2001
	S_SIGN20, // Level end sign Tails 01-14-2001
	S_SIGN21, // Level end sign Tails 01-14-2001
	S_SIGN22, // Level end sign Tails 01-14-2001
	S_SIGN23, // Level end sign Tails 01-14-2001
	S_SIGN24, // Level end sign Tails 01-14-2001
	S_SIGN25, // Level end sign Tails 01-14-2001
	S_SIGN26, // Level end sign Tails 01-14-2001
	S_SIGN27, // Level end sign Tails 01-14-2001
	S_SIGN28, // Level end sign Tails 01-14-2001
	S_SIGN29, // Level end sign Tails 01-14-2001
	S_SIGN30, // Level end sign Tails 01-14-2001
	S_SIGN31, // Level end sign Tails 01-14-2001
	S_SIGN32, // Level end sign Tails 01-14-2001
	S_SIGN33, // Level end sign Tails 01-14-2001
	S_SIGN34, // Level end sign Tails 01-14-2001
	S_SIGN35, // Level end sign Tails 01-14-2001
	S_SIGN36, // Level end sign Tails 01-14-2001
	S_SIGN37, // Level end sign Tails 01-14-2001
	S_SIGN38, // Level end sign Tails 01-14-2001
	S_SIGN39, // Level end sign Tails 01-14-2001
	S_SIGN40, // Level end sign Tails 01-14-2001
	S_SIGN41, // Level end sign Tails 01-14-2001
	S_SIGN42, // Level end sign Tails 01-14-2001
	S_SIGN43, // Level end sign Tails 01-14-2001
	S_SIGN44, // Level end sign Tails 01-14-2001
	S_SIGN45, // Level end sign Tails 01-14-2001
	S_SIGN46, // Level end sign Tails 01-14-2001
	S_SIGN47, // Level end sign Tails 01-14-2001
	S_SIGN48, // Level end sign Tails 01-14-2001
	S_SIGN49, // Level end sign Tails 01-14-2001
	S_SIGN50, // Level end sign Tails 01-14-2001
	S_SIGN51, // Level end sign Tails 01-14-2001
	S_SIGN52, // Level end sign Tails 01-14-2001
	S_SIGN53, // Level end sign Tails 01-14-2001
	S_SIGN54, // Level end sign Tails 01-14-2001
	S_SIGN55, // Level end sign Tails 01-14-2001
	S_RRNG1, // Tails 03-13-2001
	S_RRNG2, // Tails 03-13-2001
	S_RRNG3, // Tails 03-13-2001
	S_RRNG4, // Tails 03-13-2001
	S_RRNG5, // Tails 03-13-2001
	S_RRNG6, // Tails 03-13-2001
	S_RRNG7, // Tails 03-13-2001
	S_TTAG1, // Tails 05-08-2001
	S_STEAM1, // Steam riser Tails 05-28-2001
	S_STEAM2, // Steam riser Tails 05-28-2001
	S_STEAM3, // Steam riser Tails 05-28-2001
	S_STEAM4, // Steam riser Tails 05-28-2001
	S_STEAM5, // Steam riser Tails 05-28-2001
	S_STEAM6, // Steam riser Tails 05-28-2001
	S_STEAM7, // Steam riser Tails 05-28-2001
	S_STEAM8, // Steam riser Tails 05-28-2001
	S_REDFLAG, // Red CTF Flag Tails 07-22-2001
	S_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	S_GOTFLAG1, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG2, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG3, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG4, // Got Flag sign Tails 07-22-2001
	S_TOKEN, // Special Stage Token Tails 08-11-2001
	S_TOKEN2, // Special Stage Token Tails 08-17-2001
	S_CEMG, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMO, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMP, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMB, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMR, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEML, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMY, // Chaos Emerald (intangible) Tails 08-18-2001
	S_JETBLOOK1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBLOOK2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETGLOOK1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGLOOK2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETBULLET1, // Jetty-Syn Bullet Tails 08-25-2001
	S_JETBULLET2, // Jetty-Syn Bullet Tails 08-25-2001
	S_MOUSE1, // Mouse Tails 08-26-2001
	S_MOUSE2, // Mouse Tails 08-26-2001
	S_DETON1, // Deton Tails 08-26-2001
	S_DETON2, // Deton Tails 08-26-2001
	S_DETON3, // Deton Tails 08-26-2001
	S_DETON4, // Deton Tails 08-26-2001
	S_DETON5, // Deton Tails 08-26-2001
	S_DETON6, // Deton Tails 08-26-2001
	S_DETON7, // Deton Tails 08-26-2001
	S_DETON8, // Deton Tails 08-26-2001
	S_DETON9, // Deton Tails 08-26-2001
	S_DETON10, // Deton Tails 08-26-2001
	S_DETON11, // Deton Tails 08-26-2001
	S_DETON12, // Deton Tails 08-26-2001
	S_DETON13, // Deton Tails 08-26-2001
	S_DETON14, // Deton Tails 08-26-2001
	S_DETON15, // Deton Tails 08-26-2001
	S_XPLD1, // Robot Explosion Tails 08-26-2001
	S_XPLD2, // Robot Explosion Tails 08-26-2001
	S_XPLD3, // Robot Explosion Tails 08-26-2001
	S_XPLD4, // Robot Explosion Tails 08-26-2001
	S_CEZCHAIN, // CEZ Chain Tails 11-02-2001
	S_CAPE1, // Fake little Super Sonic cape Tails 11-12-2001
	S_CAPE2, // Fake little Super Sonic cape Tails 11-12-2001
	S_SNOW1, // Snowflake Tails 12-02-2001
	S_SNOW2, // Snowflake Tails 12-02-2001
	S_SNOW3, // Snowflake Tails 12-02-2001
	S_SANTA1, // Santa Tails 12-12-2001
	S_EMER1, // Emerald Hunt 1 Tails 12-12-2001
	S_EMES1, // Emerald Hunt 2 Tails 12-12-2001
	S_EMET1, // Emerald Hunt 3 Tails 12-12-2001
	S_SBLL1, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SBLL2, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SPIKEBALL1, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL2, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL3, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL4, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL5, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL6, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL7, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL8, // Spike Ball Tails 12-18-2001
	S_CCOMMAND1, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND2, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND3, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND4, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND5, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND6, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND7, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND8, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND9, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND10, // Crawla Commander Tails 12-30-2001
	S_CRUMBLE1, // Tails 03-16-2002
	S_CRUMBLE2, // Tails 03-16-2002
	S_RAIN1, // Rain Tails 06-07-2002
	S_RAINRETURN, // Tails 12-09-2002
	S_CEILINGSPIKE, // Tails 06-15-2002
	S_FLOORSPIKE, // Tails 06-15-2002
	S_STARPOST1, // Tails 07-03-2002
	S_STARPOST2,
	S_STARPOST3,
	S_STARPOST4,
	S_STARPOST5,
	S_STARPOST6,
	S_STARPOST7,
	S_STARPOST8,
	S_STARPOST9,
	S_STARPOST10,
	S_STARPOST11,
	S_STARPOST12,
	S_STARPOST13,
	S_STARPOST14,
	S_STARPOST15,
	S_STARPOST16,
	S_STARPOST17,
	S_STARPOST18,
	S_STARPOST19,
	S_STARPOST20,
	S_STARPOST21,
	S_STARPOST22,
	S_STARPOST23,
	S_STARPOST24,
	S_STARPOST25,
	S_STARPOST26,
	S_STARPOST27,
	S_STARPOST28,
	S_STARPOST29,
	S_STARPOST30,
	S_STARPOST31,
	S_STARPOST32,
	S_STARPOST33,
	S_STARPOST34,
	S_HOMINGRING1,
	S_HOMINGRING2,
	S_HOMINGRING3,
	S_HOMINGRING4,
	S_HOMINGRING5,
	S_HOMINGRING6,
	S_HOMINGRING7,
	S_HOMINGRING8,
	S_HOMINGRING9,
	S_HOMINGRING10,
	S_HOMINGRING11,
	S_HOMINGRING12,
	S_HOMINGRING13,
	S_HOMINGRING14,
	S_HOMINGRING15,
	S_HOMINGRING16,
	S_HOMINGRING17,
	S_HOMINGRING18,
	S_HOMINGRING19,
	S_HOMINGRING20,
	S_HOMINGRING21,
	S_HOMINGRING22,
	S_HOMINGRING23,
	S_HOMINGRING24,
	S_HOMINGRING25,
	S_HOMINGRING26,
	S_HOMINGRING27,
	S_HOMINGRING28,
	S_HOMINGRING29,
	S_HOMINGRING30,
	S_HOMINGRING31,
	S_HOMINGRING32,
	S_HOMINGRING33,
	S_HOMINGRING34,
	S_HOMINGRING35,
	S_RAILRING1,
	S_RAILRING2,
	S_RAILRING3,
	S_RAILRING4,
	S_RAILRING5,
	S_RAILRING6,
	S_RAILRING7,
	S_RAILRING8,
	S_RAILRING9,
	S_RAILRING10,
	S_RAILRING11,
	S_RAILRING12,
	S_RAILRING13,
	S_RAILRING14,
	S_RAILRING15,
	S_RAILRING16,
	S_RAILRING17,
	S_RAILRING18,
	S_RAILRING19,
	S_RAILRING20,
	S_RAILRING21,
	S_RAILRING22,
	S_RAILRING23,
	S_RAILRING24,
	S_RAILRING25,
	S_RAILRING26,
	S_RAILRING27,
	S_RAILRING28,
	S_RAILRING29,
	S_RAILRING30,
	S_RAILRING31,
	S_RAILRING32,
	S_RAILRING33,
	S_RAILRING34,
	S_RAILRING35,
	S_SHIELDRING1,
	S_SHIELDRING2,
	S_SHIELDRING3,
	S_SHIELDRING4,
	S_SHIELDRING5,
	S_SHIELDRING6,
	S_SHIELDRING7,
	S_SHIELDRING8,
	S_SHIELDRING9,
	S_SHIELDRING10,
	S_SHIELDRING11,
	S_SHIELDRING12,
	S_SHIELDRING13,
	S_SHIELDRING14,
	S_SHIELDRING15,
	S_SHIELDRING16,
	S_SHIELDRING17,
	S_SHIELDRING18,
	S_SHIELDRING19,
	S_SHIELDRING20,
	S_SHIELDRING21,
	S_SHIELDRING22,
	S_SHIELDRING23,
	S_SHIELDRING24,
	S_SHIELDRING25,
	S_SHIELDRING26,
	S_SHIELDRING27,
	S_SHIELDRING28,
	S_SHIELDRING29,
	S_SHIELDRING30,
	S_SHIELDRING31,
	S_SHIELDRING32,
	S_SHIELDRING33,
	S_SHIELDRING34,
	S_SHIELDRING35,
	S_AUTOMATICRING1,
	S_AUTOMATICRING2,
	S_AUTOMATICRING3,
	S_AUTOMATICRING4,
	S_AUTOMATICRING5,
	S_AUTOMATICRING6,
	S_AUTOMATICRING7,
	S_AUTOMATICRING8,
	S_AUTOMATICRING9,
	S_AUTOMATICRING10,
	S_AUTOMATICRING11,
	S_AUTOMATICRING12,
	S_AUTOMATICRING13,
	S_AUTOMATICRING14,
	S_AUTOMATICRING15,
	S_AUTOMATICRING16,
	S_AUTOMATICRING17,
	S_AUTOMATICRING18,
	S_AUTOMATICRING19,
	S_AUTOMATICRING20,
	S_AUTOMATICRING21,
	S_AUTOMATICRING22,
	S_AUTOMATICRING23,
	S_AUTOMATICRING24,
	S_AUTOMATICRING25,
	S_AUTOMATICRING26,
	S_AUTOMATICRING27,
	S_AUTOMATICRING28,
	S_AUTOMATICRING29,
	S_AUTOMATICRING30,
	S_AUTOMATICRING31,
	S_AUTOMATICRING32,
	S_AUTOMATICRING33,
	S_AUTOMATICRING34,
	S_AUTOMATICRING35,
	S_EXPLOSIONRING1,
	S_EXPLOSIONRING2,
	S_EXPLOSIONRING3,
	S_EXPLOSIONRING4,
	S_EXPLOSIONRING5,
	S_EXPLOSIONRING6,
	S_EXPLOSIONRING7,
	S_EXPLOSIONRING8,
	S_EXPLOSIONRING9,
	S_EXPLOSIONRING10,
	S_EXPLOSIONRING11,
	S_EXPLOSIONRING12,
	S_EXPLOSIONRING13,
	S_EXPLOSIONRING14,
	S_EXPLOSIONRING15,
	S_EXPLOSIONRING16,
	S_EXPLOSIONRING17,
	S_EXPLOSIONRING18,
	S_EXPLOSIONRING19,
	S_EXPLOSIONRING20,
	S_EXPLOSIONRING21,
	S_EXPLOSIONRING22,
	S_EXPLOSIONRING23,
	S_EXPLOSIONRING24,
	S_EXPLOSIONRING25,
	S_EXPLOSIONRING26,
	S_EXPLOSIONRING27,
	S_EXPLOSIONRING28,
	S_EXPLOSIONRING29,
	S_EXPLOSIONRING30,
	S_EXPLOSIONRING31,
	S_EXPLOSIONRING32,
	S_EXPLOSIONRING33,
	S_EXPLOSIONRING34,
	S_EXPLOSIONRING35,
	S_THROWNAUTOMATICEXPLOSIONHOMING1,
	S_THROWNAUTOMATICEXPLOSIONHOMING2,
	S_THROWNAUTOMATICEXPLOSIONHOMING3,
	S_THROWNAUTOMATICEXPLOSIONHOMING4,
	S_THROWNAUTOMATICEXPLOSIONHOMING5,
	S_THROWNAUTOMATICEXPLOSIONHOMING6,
	S_THROWNAUTOMATICEXPLOSIONHOMING7,
	S_THROWNAUTOMATICEXPLOSION1,
	S_THROWNAUTOMATICEXPLOSION2,
	S_THROWNAUTOMATICEXPLOSION3,
	S_THROWNAUTOMATICEXPLOSION4,
	S_THROWNAUTOMATICEXPLOSION5,
	S_THROWNAUTOMATICEXPLOSION6,
	S_THROWNAUTOMATICEXPLOSION7,
	S_THROWNAUTOMATICHOMING1,
	S_THROWNAUTOMATICHOMING2,
	S_THROWNAUTOMATICHOMING3,
	S_THROWNAUTOMATICHOMING4,
	S_THROWNAUTOMATICHOMING5,
	S_THROWNAUTOMATICHOMING6,
	S_THROWNAUTOMATICHOMING7,
	S_THROWNHOMINGEXPLOSION1,
	S_THROWNHOMINGEXPLOSION2,
	S_THROWNHOMINGEXPLOSION3,
	S_THROWNHOMINGEXPLOSION4,
	S_THROWNHOMINGEXPLOSION5,
	S_THROWNHOMINGEXPLOSION6,
	S_THROWNHOMINGEXPLOSION7,
	S_THROWNHOMING1,
	S_THROWNHOMING2,
	S_THROWNHOMING3,
	S_THROWNHOMING4,
	S_THROWNHOMING5,
	S_THROWNHOMING6,
	S_THROWNHOMING7,
	S_THROWNAUTOMATIC1,
	S_THROWNAUTOMATIC2,
	S_THROWNAUTOMATIC3,
	S_THROWNAUTOMATIC4,
	S_THROWNAUTOMATIC5,
	S_THROWNAUTOMATIC6,
	S_THROWNAUTOMATIC7,
	S_THROWNEXPLOSION1,
	S_THROWNEXPLOSION2,
	S_THROWNEXPLOSION3,
	S_THROWNEXPLOSION4,
	S_THROWNEXPLOSION5,
	S_THROWNEXPLOSION6,
	S_THROWNEXPLOSION7,
	S_RINGEXPLODE,
	S_BERRYBUSH,
	S_BUSH,
	S_GFZFLOWERB1,
	S_GFZFLOWERB2,
	S_GFZFLOWERC1,
	S_MIXUPBOX1,
	S_MIXUPBOX2,
	S_MIXUPBOX3,
	S_MIXUPBOX4,
	S_RANDOMBOX1,
	S_RANDOMBOX2,
	S_RANDOMBOX3,
	S_MONITOREXPLOSION1,
	S_MONITOREXPLOSION2,
	S_MONITOREXPLOSION3,
	S_MONITOREXPLOSION4,
	S_MONITOREXPLOSION5,
	S_FLAME1, // Flame (has corona) Tails 09-06-2002
	S_FLAME2, // Flame (has corona) Tails 09-06-2002
	S_FLAME3, // Flame (has corona) Tails 09-06-2002
	S_FLAME4, // Flame (has corona) Tails 09-06-2002
	S_LASER1,
	S_LASER2,
	S_LASER3,
	S_LASER4,

	// Mario-specific stuff Tails 09-10-2002
	S_PUMA1,
	S_PUMA2,
	S_PUMA3,
	S_PUMA4,
	S_PUMA5,
	S_PUMA6,
	S_HAMMER1,
	S_HAMMER2,
	S_HAMMER3,
	S_HAMMER4,
	S_KOOPA1,
	S_KOOPA2,
	S_SHELL,
	S_SHELL1,
	S_SHELL2,
	S_SHELL3,
	S_SHELL4,
	S_AXE1,
	S_AXE2,
	S_AXE3,
	S_KOOPAFLAME1,
	S_KOOPAFLAME2,
	S_KOOPAFLAME3,
	S_FIREBALL1,
	S_FIREBALL2,
	S_FIREBALL3,
	S_FIREBALL4,
	S_FIREBALLEXP1,
	S_FIREBALLEXP2,
	S_FIREBALLEXP3,
	S_FIREFLOWER1,
	S_FIREFLOWER2,
	S_FIREFLOWER3,
	S_FIREFLOWER4,

	S_NIGHTSPARKLE1,
	S_NIGHTSPARKLE2,
	S_NIGHTSPARKLE3,
	S_NIGHTSPARKLE4,

	S_NIGHTSDRONE1,
	S_NIGHTSDRONE2,

	S_NIGHTSFLY1A,
	S_NIGHTSFLY1B,
	S_NIGHTSFLY2A,
	S_NIGHTSFLY2B,
	S_NIGHTSFLY3A,
	S_NIGHTSFLY3B,
	S_NIGHTSFLY4A,
	S_NIGHTSFLY4B,
	S_NIGHTSFLY5A,
	S_NIGHTSFLY5B,
	S_NIGHTSFLY6A,
	S_NIGHTSFLY6B,
	S_NIGHTSFLY7A,
	S_NIGHTSFLY7B,
	S_NIGHTSFLY8A,
	S_NIGHTSFLY8B,
	S_NIGHTSFLY9A,
	S_NIGHTSFLY9B,

	S_NIGHTSHURT1,
	S_NIGHTSHURT2,
	S_NIGHTSHURT3,
	S_NIGHTSHURT4,
	S_NIGHTSHURT5,
	S_NIGHTSHURT6,
	S_NIGHTSHURT7,
	S_NIGHTSHURT8,
	S_NIGHTSHURT9,
	S_NIGHTSHURT10,
	S_NIGHTSHURT11,
	S_NIGHTSHURT12,
	S_NIGHTSHURT13,
	S_NIGHTSHURT14,
	S_NIGHTSHURT15,
	S_NIGHTSHURT16,
	S_NIGHTSHURT17,
	S_NIGHTSHURT18,
	S_NIGHTSHURT19,
	S_NIGHTSHURT20,
	S_NIGHTSHURT21,
	S_NIGHTSHURT22,
	S_NIGHTSHURT23,
	S_NIGHTSHURT24,
	S_NIGHTSHURT25,
	S_NIGHTSHURT26,
	S_NIGHTSHURT27,
	S_NIGHTSHURT28,
	S_NIGHTSHURT29,
	S_NIGHTSHURT30,
	S_NIGHTSHURT31,
	S_NIGHTSHURT32,

	S_NIGHTSDRILL1A,
	S_NIGHTSDRILL1B,
	S_NIGHTSDRILL1C,
	S_NIGHTSDRILL1D,
	S_NIGHTSDRILL2A,
	S_NIGHTSDRILL2B,
	S_NIGHTSDRILL2C,
	S_NIGHTSDRILL2D,
	S_NIGHTSDRILL3A,
	S_NIGHTSDRILL3B,
	S_NIGHTSDRILL3C,
	S_NIGHTSDRILL3D,
	S_NIGHTSDRILL4A,
	S_NIGHTSDRILL4B,
	S_NIGHTSDRILL4C,
	S_NIGHTSDRILL4D,
	S_NIGHTSDRILL5A,
	S_NIGHTSDRILL5B,
	S_NIGHTSDRILL5C,
	S_NIGHTSDRILL5D,
	S_NIGHTSDRILL6A,
	S_NIGHTSDRILL6B,
	S_NIGHTSDRILL6C,
	S_NIGHTSDRILL6D,
	S_NIGHTSDRILL7A,
	S_NIGHTSDRILL7B,
	S_NIGHTSDRILL7C,
	S_NIGHTSDRILL7D,
	S_NIGHTSDRILL8A,
	S_NIGHTSDRILL8B,
	S_NIGHTSDRILL8C,
	S_NIGHTSDRILL8D,
	S_NIGHTSDRILL9A,
	S_NIGHTSDRILL9B,
	S_NIGHTSDRILL9C,
	S_NIGHTSDRILL9D,

	S_SEED,

	S_JETFUME1,
	S_JETFUME2,
	S_JETFUME3,
	S_JETFUME4,

	S_HOOP,
	S_NIGHTSCORE10,
	S_NIGHTSCORE20,
	S_NIGHTSCORE30,
	S_NIGHTSCORE40,
	S_NIGHTSCORE50,
	S_NIGHTSCORE60,
	S_NIGHTSCORE70,
	S_NIGHTSCORE80,
	S_NIGHTSCORE90,
	S_NIGHTSCORE100,

	S_NIGHTSWING,
	
	// Boss 2 Tails 11-14-02
    S_EGGMOBILE2_STND,
	S_EGGMOBILE2_POGO1,
	S_EGGMOBILE2_POGO2,
	S_EGGMOBILE2_POGO3,
	S_EGGMOBILE2_POGO4,
    S_EGGMOBILE2_PAIN,
    S_EGGMOBILE2_PAIN2,
    S_EGGMOBILE2_PAIN3,
    S_EGGMOBILE2_PAIN4,
    S_EGGMOBILE2_PAIN5,
    S_EGGMOBILE2_PAIN6,
    S_EGGMOBILE2_PAIN7,
    S_EGGMOBILE2_PAIN8,
    S_EGGMOBILE2_PAIN9,
    S_EGGMOBILE2_PAIN10,
    S_EGGMOBILE2_PAIN11,
    S_EGGMOBILE2_PAIN12,
    S_EGGMOBILE2_DIE1,
    S_EGGMOBILE2_DIE2,
    S_EGGMOBILE2_DIE3,
    S_EGGMOBILE2_DIE4,
    S_EGGMOBILE2_DIE5,
    S_EGGMOBILE2_DIE6,
    S_EGGMOBILE2_DIE7,
    S_EGGMOBILE2_DIE8,
    S_EGGMOBILE2_DIE9,
    S_EGGMOBILE2_DIE10,
    S_EGGMOBILE2_DIE11,
    S_EGGMOBILE2_DIE12,
    S_EGGMOBILE2_DIE13,
    S_EGGMOBILE2_DIE14,
	S_EGGMOBILE2_FLEE1,
	S_EGGMOBILE2_FLEE2,
	S_GOOP1,
	S_GOOP2,
	S_GOOP3,
	S_BPLD1,
	S_BPLD2,
	S_BPLD3,
	S_BPLD4,
	S_BPLD5,
	S_BPLD6,
	S_BPLD7,
	S_ALARM1,
	S_EMBLEM1,
	S_EMBLEM2,
	S_EMBLEM3,
	S_EMBLEM4,
	S_EMBLEM5,
	S_EMBLEM6,
	S_EMBLEM7,
	S_EMBLEM8,
	S_EMBLEM9,
	S_EMBLEM10,
	S_EMBLEM11,
	S_EMBLEM12,
	S_EMBLEM13,
	S_EMBLEM14,
	S_EMBLEM15,
	S_EMBLEM16,
	S_EMBLEM17,
	S_EMBLEM18,
	S_EMBLEM19,
	S_EMBLEM20,

    S_EGGTV1,
    S_EGGTV2,
    S_EGGTV3,
    S_EGGTV4,

	S_SPINFIRE1,
	S_SPINFIRE2,
	S_SPINFIRE3,
	S_SPINFIRE4,
	S_SPINFIRE5,
	S_SPINFIRE6,

	S_BOSSTANK1,
	S_BOSSTANK2,
	S_BOSSSPIGOT,

	S_FOG1,
	S_FOG2,
	S_FOG3,
	S_FOG4,
	S_FOG5,
	S_FOG6,
	S_FOG7,
	S_FOG8,
	S_FOG9,
	S_FOG10,
	S_FOG11,
	S_FOG12,
	S_FOG13,
	S_FOG14,
	S_EEGG,
	S_LITE, // Tails 02-18-2003

	S_TURRET,
	S_TURRETFIRE,
	S_TURRETSHOCK1,
	S_TURRETSHOCK2,
	S_TURRETSHOCK3,
	S_TURRETSHOCK4,
	S_TURRETSHOCK5,
	S_TURRETSHOCK6,
	S_TURRETSHOCK7,
	S_TURRETSHOCK8,
	S_TURRETSHOCK9,

	S_TURRETLASER,
	S_TURRETLASEREXPLODE1,
	S_TURRETLASEREXPLODE2,

	S_GFZFLOWERD1,

	S_GOOMBA1,
	S_GOOMBA1B,
	S_GOOMBA2,
	S_GOOMBA3,
	S_GOOMBA4,
	S_GOOMBA5,
	S_GOOMBA6,
	S_GOOMBA7,
	S_GOOMBA8,
	S_GOOMBA9,
	S_GOOMBA_DEAD,
	S_BLUEGOOMBA1,
	S_BLUEGOOMBA1B,
	S_BLUEGOOMBA2,
	S_BLUEGOOMBA3,
	S_BLUEGOOMBA4,
	S_BLUEGOOMBA5,
	S_BLUEGOOMBA6,
	S_BLUEGOOMBA7,
	S_BLUEGOOMBA8,
	S_BLUEGOOMBA9,
	S_BLUEGOOMBA_DEAD,
	S_MARIOBUSH1,
	S_MARIOBUSH2,
	S_TOAD,
	S_COIN1,
	S_COIN2,
	S_COIN3,
	S_COINSPARKLE1,
	S_COINSPARKLE2,
	S_COINSPARKLE3,
	S_COINSPARKLE4,
	
	S_XMASPOLE,
	S_CANDYCANE,
	S_SNOWMAN,

	S_EGGCAPSULE,

	S_SUPERTRANS1,
	S_SUPERTRANS2,
	S_SUPERTRANS3,
	S_SUPERTRANS4,
	S_SUPERTRANS5,
	S_SUPERTRANS6,
	S_SUPERTRANS7,
	S_SUPERTRANS8,
	S_SUPERTRANS9,

	S_ROCKCRUMBLE1,
	S_ROCKCRUMBLE2,
	S_ROCKCRUMBLE3,
	S_ROCKCRUMBLE4,
	S_ROCKCRUMBLE5,

	// NiGHTS Paraloop Powerups Tails 12-15-2003
	S_NIGHTSPOWERUP1,
	S_NIGHTSPOWERUP2,
	S_NIGHTSPOWERUP3,
	S_NIGHTSPOWERUP4,
	S_NIGHTSPOWERUP5,
	S_NIGHTSPOWERUP6,

	S_NIGHTSCORE10_2,
	S_NIGHTSCORE20_2,
	S_NIGHTSCORE30_2,
	S_NIGHTSCORE40_2,
	S_NIGHTSCORE50_2,
	S_NIGHTSCORE60_2,
	S_NIGHTSCORE70_2,
	S_NIGHTSCORE80_2,
	S_NIGHTSCORE90_2,
	S_NIGHTSCORE100_2,

	// Hyper Sonic Spark Tails 12-22-2003
    S_HSPK1,
    S_HSPK2,
    S_HSPK3,
    S_HSPK4,
    S_HSPK5,

	S_REDXVI, // He's BACK!

    NUMSTATES
} statenum_t;

typedef struct
{
  spritenum_t   sprite;
  long          frame;          //faB: we use the upper 16bits for translucency
                                //     and other shade effects
  long          tics;
  // void       (*action) ();
  actionf_t     action;
  statenum_t    nextstate;
//  long          misc1, misc2;
} state_t;

extern state_t  states[NUMSTATES];
extern char *sprnames[NUMSPRITES+1];



typedef enum {
    MT_PLAYER,
    MT_BLUECRAWLA,
    MT_REDCRAWLA,
    MT_EGGMOBILE,
    MT_ROCKET,
    MT_RING,
    MT_SUPERRINGBOX,
    MT_GREYRINGBOX,
    MT_EMMY, // emerald tails
    MT_INV,
    MT_GREENTV,
    MT_FAN,
    MT_BUBBLES, // Bubble source Tails 03-07-2000
    MT_GFZFLOWER1,
    MT_YELLOWTV,
    MT_BLUETV,
	MT_REDTV,
    MT_YELLOWSPRING,
    MT_SNEAKERTV,
    MT_REDSPRING,
    MT_CHASECAM,
    MT_SPIRIT,
    MT_SMOK,        // test lave/slime damage smoke
    MT_SPLASH,      // test water splash
    MT_PUSH,    //SoM: 3/8/2000: controls push source
    MT_PULL,    //SoM: 3/8/2000: controls pull source
	MT_FLINGRING,   //SOM: Test rings flying
    MT_BIRD, // Tails 10-20-99 Birdie freed!
    MT_SQRL, // Tails 10-20-99 Squirrel freed!
    MT_BLUEORB, // Tails 12-29-99 shield mobjs
	MT_REDORB, // Tails 12-18-2002
    MT_YELLOWORB, // Tails 12-29-99 shield mobjs
    MT_GREENORB, // Tails 12-29-99 shield mobjs
    MT_BLACKORB, // Tails 12-29-99 shield mobjs
    MT_SPARK, //spark tails
    MT_IVSP, // invincibility sparkles tails
    MT_IVSQ, // invincibility sparkles finish tails
    MT_DISS, // dissipating object tails
    MT_SMALLBUBBLE, // small bubble Tails 03-07-2000
    MT_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
    MT_EXTRALARGEBUBBLE, // extra large bubble Tails 03-07-2000
    MT_ZERO, // Drowning Timer - 0 Tails 03-07-2000
    MT_ONE, // Drowning Timer - 1 Tails 03-07-2000
    MT_TWO, // Drowning Timer - 2 Tails 03-07-2000
    MT_THREE, // Drowning Timer - 3 Tails 03-07-2000
    MT_FOUR, // Drowning Timer - 4 Tails 03-07-2000
    MT_FIVE, // Drowning Timer - 5 Tails 03-07-2000
    MT_POP, // Extra Large bubble goes POP! Tails 03-08-2000
    MT_PRUP, // 1up Box Tails 03-12-2000
    MT_BLACKTV, // Black shield TV Tails 04-08-2000
    MT_SCRA, // 100 score logo Tails 04-16-2000
    MT_SCRB, // 200 score logo Tails 04-16-2000
    MT_SCRC, // 500 score logo Tails 04-16-2000
    MT_SCRD, // 1000 score logo Tails 04-16-2000
    MT_SUPERSPARK, // Super Sonic Spark Tails 04-18-2000
    MT_GRASSDEBRIS, // Grass debris Tails 05-14-2000
    MT_YELLOWDIAG, // Yellow Diagonal Spring Tails 05-17-2000
	MT_REDDIAG, // Red Diagonal Spring Tails 05-27-2003
    MT_AWATERA, // Ambient Water Sound 1 Tails 06-10-2000
    MT_AWATERB, // Ambient Water Sound 2 Tails 06-10-2000
    MT_AWATERC, // Ambient Water Sound 3 Tails 06-10-2000
    MT_AWATERD, // Ambient Water Sound 4 Tails 06-10-2000
    MT_AWATERE, // Ambient Water Sound 5 Tails 06-10-2000
    MT_AWATERF, // Ambient Water Sound 6 Tails 06-10-2000
    MT_AWATERG, // Ambient Water Sound 7 Tails 06-10-2000
    MT_AWATERH, // Ambient Water Sound 8 Tails 06-10-2000
    MT_SKIM, // Skim mine dropper Tails 06-13-2000
    MT_MINE, // Skim mine Tails 06-13-2000
    MT_GFZFISH, // Greenflower Fish Tails 07-03-2000
    MT_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	MT_SPLISH, // Water splish! Tails 12-08-2000
    MT_THOK, // Tails 12-05-99 Thok! mobj
	MT_THZPLANT, // THZ Plant Tails 12-19-2000
	MT_SIGN, // Level end sign Tails 01-14-2001
	MT_REDRING, // Tails 03-13-2001
	MT_TAG, // Tag Sign Tails 05-08-2001
	MT_STEAM, // Steam riser Tails 05-28-2001
	MT_REDFLAG, // Red CTF Flag Tails 07-22-2001
	MT_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	MT_GOTFLAG, // Got Flag sign Tails 07-22-2001
	MT_GOTFLAG2, // Got Flag sign Tails 08-02-2001
	MT_TOKEN, // Special Stage Token Tails 08-11-2001
	MT_GREENEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_ORANGEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_PINKEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_BLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_REDEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_LIGHTBLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_GREYEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_JETTBOMBER, // Jetty-Syn Bomber Tails 08-18-2001
	MT_JETTGUNNER, // Jetty-Syn Gunner Tails 08-25-2001
	MT_JETTBULLET, // Jetty-Syn Bullet Tails 08-25-2001
	MT_MOUSE, // Mouse Tails 08-26-2001
	MT_DETON, // Deton Tails 08-26-2001
	MT_EXPLODE, // Robot Explosion Tails 08-26-2001
	MT_CHAIN, // CEZ Chain Tails 11-02-2001
	MT_CAPE, // Fake little Super Sonic cape Tails 11-12-2001
	MT_SNOWFLAKE, // Snowflake Tails 12-02-2001
	MT_SANTA, // Santa Tails 12-12-2001
	MT_EMERHUNT, // Emerald Hunt 1 Tails 12-12-2001
	MT_EMESHUNT, // Emerald Hunt 2 Tails 12-12-2001
	MT_EMETHUNT, // Emerald Hunt 3 Tails 12-12-2001
	MT_SNOWBALL, // Snow Ball for Snow Buster Tails 12-12-2001
	MT_SPIKEBALL, // Spike Ball Tails 12-18-2001
	MT_CRAWLACOMMANDER, // Crawla Commander Tails 12-30-2001
	MT_CRUMBLEOBJ, // Sound generator for crumbling platform Tails 03-16-2002
    MT_YELLOWDIAGDOWN, // Yellow Diagonal Upside-Down Spring Tails 05-28-2002
	MT_REDDIAGDOWN, // Red Diagonal Upside-Down Spring Tails 05-27-2003
	MT_YELLOWSPRINGDOWN,
	MT_REDSPRINGDOWN,
	MT_RAIN, // Rain Tails 06-07-2002
	MT_CEILINGSPIKE, // Tails 06-15-2002
	MT_FLOORSPIKE, // Tails 06-15-2002
	MT_STARPOST, // Tails 07-03-2002
	MT_SPECIALSPIKEBALL, // Tails 07-06-2002
	MT_HOMINGRING,
	MT_RAILRING,
	MT_SHIELDRING,
	MT_AUTOMATICRING,
	MT_EXPLOSIONRING,
	MT_THROWNAUTOMATICEXPLOSIONHOMING,
	MT_THROWNAUTOMATICEXPLOSION,
	MT_THROWNAUTOMATICHOMING,
	MT_THROWNHOMINGEXPLOSION,
	MT_THROWNHOMING,
	MT_THROWNAUTOMATIC,
	MT_THROWNEXPLOSION,
	MT_BERRYBUSH,
	MT_BUSH,
	MT_GFZFLOWER2,
	MT_GFZFLOWER3,
	MT_MIXUPBOX,
	MT_QUESTIONBOX,
	MT_MONITOREXPLOSION,
	MT_RINGICO,
	MT_SRINGICO,
	MT_1UPICO,
	MT_BSHIELDICO,
	MT_GSHIELDICO,
	MT_YSHIELDICO,
	MT_KSHIELDICO,
	MT_RSHIELDICO,
	MT_INVCICO,
	MT_MIXUPICO,
	MT_SHOESICO,
	MT_FLAME, // Flame (has corona) Tails 09-06-2002
	MT_LASER,

	// Mario-specific stuff Tails 09-10-2002
	MT_PUMA,
	MT_HAMMER,
	MT_KOOPA,
	MT_SHELL,
	MT_AXE,
	MT_KOOPAFLAME,
	MT_FIREBALL,
	MT_FIREFLOWER,

	MT_NIGHTSPARKLE,
	MT_AXIS1,
	MT_AXIS2,
	MT_AXIS3,
	MT_AXIS1A,
	MT_AXIS2A,
	MT_AXIS3A,
	MT_AXISTRANSFER,
	MT_AXISTRANSFERCONDITION,
	MT_AXISTRANSFERCONDITION2,
	MT_AXISTRANSFERCLOSEST,
	MT_AXISTRANSFERTOLAST,
	MT_NIGHTSDRONE,
	MT_NIGHTSCHAR,

	MT_SEED,
	MT_JETFUME1,
	MT_JETFUME2,
	MT_HOOP,
	MT_HOOPCOLLIDE, // Collision detection for NiGHTS hoops
	MT_HOOPCENTER, // Center of a hoop
	MT_NIGHTSCORE,
	MT_NIGHTSWING,
	MT_BOSSFLYPOINT,
	MT_EGGMOBILE2,
	MT_GOOP,
	MT_BOSSEXPLODE,
	MT_EGGTRAP,
	MT_CHAOSSPAWNER,
	MT_ALARM,
	MT_EMBLEM,
	MT_EGGMANBOX,
	MT_EGGMANICO,
	MT_SPINFIRE,
	MT_BOSSTANK1,
	MT_BOSSTANK2,
	MT_BOSSSPIGOT,
	MT_TFOG,
	MT_EASTEREGG,
	MT_STREETLIGHT,
	MT_TURRET,
	MT_TURRETLASER,
	MT_GFZFLOWER4,

	MT_GOOMBA,
	MT_BLUEGOOMBA,
	MT_MARIOBUSH1,
	MT_MARIOBUSH2,
	MT_TOAD,
	MT_COIN,
	MT_COINSPARKLE,
	MT_FLINGCOIN,

	MT_XMASPOLE,
	MT_CANDYCANE,
	MT_SNOWMAN,
	MT_EGGCAPSULE,

	MT_SUPERTRANS,

	MT_RANDOMAMBIENT,

	MT_ROCKCRUMBLE,

	MT_TELEPORTMAN, // Graue 11-05-2003

	// NiGHTS Paraloop Powerups Tails 12-15-2003
	MT_NIGHTSSUPERLOOP,
	MT_NIGHTSDRILLREFILL,
	MT_NIGHTSHELPER,

	MT_HYPERSPARK,

	MT_REDXVI, // He's BACK!

	MT_SLOPETHINGY, // experimental slope thingy

    NUMMOBJTYPES

} mobjtype_t;

typedef struct
{
    int doomednum;
    int spawnstate;
    int spawnhealth;
    int seestate;
    int seesound;
    int reactiontime;
    int attacksound;
    int painstate;
    int painchance;
    int painsound;
    int meleestate;
    int missilestate;
    int deathstate;
    int xdeathstate;
    int deathsound;
    int speed;
    int radius;
    int height;
    int mass;
    int damage;
    int activesound;
    int flags;
    int raisestate;
} mobjinfo_t;

extern mobjinfo_t mobjinfo[NUMMOBJTYPES];

void P_PatchInfoTables( void );

#endif
