// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id: sounds.c,v 1.10 2001/03/30 17:12:51 bpereira Exp $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Portions Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// $Log: sounds.c,v $
// Revision 1.10  2001/03/30 17:12:51  bpereira
// no message
//
// Revision 1.9  2001/03/13 22:14:20  stroggonmeth
// Long time no commit. 3D floors, FraggleScript, portals, ect.
//
// Revision 1.8  2001/02/24 13:35:21  bpereira
// no message
//
// Revision 1.7  2001/01/25 22:15:44  bpereira
// added heretic support
//
// Revision 1.6  2000/11/21 21:13:18  stroggonmeth
// Optimised 3D floors and fixed crashing bug in high resolutions.
//
// Revision 1.5  2000/11/03 11:48:40  hurdler
// Fix compiling problem under win32 with 3D-Floors and FragglScript (to verify!)
//
// Revision 1.4  2000/11/03 02:37:36  stroggonmeth
// Fix a few warnings when compiling.
//
// Revision 1.3  2000/11/02 17:50:10  stroggonmeth
// Big 3Dfloors & FraggleScript commit!!
//
// Revision 1.2  2000/02/27 00:42:11  hurdler
// fix CR+LF problem
//
// Revision 1.1.1.1  2000/02/22 20:32:32  hurdler
// Initial import into CVS (v1.29 pr3)
//
//
// DESCRIPTION:
//      music/sound tables, and related sound routines
//
// Note: the tables were originally created by a sound utility at Id,
//       kept as a sample, DOOM2 sounds.
//
//-----------------------------------------------------------------------------


#include "doomtype.h"
#include "i_sound.h"
#include "sounds.h"
#include "r_defs.h"
#include "r_things.h"
#include "z_zone.h"
#include "w_wad.h"

extern boolean nofmod;

// NOTE: add \0 for stringlen=6, to allow dehacked patching

//
// Information about all the music
//

musicinfo_t S_music[NUMMUSIC] =
{
    { 0 },
    { "map01m"  , 0 },
	{ "map02m"  , 0 },
	{ "map03m"  , 0 },
	{ "map04m"  , 0 },
	{ "map05m"  , 0 },
	{ "map06m"  , 0 },
	{ "map07m"  , 0 },
	{ "map08m"  , 0 },
	{ "map09m"  , 0 },
	{ "map10m"  , 0 },
	{ "map11m"  , 0 },
	{ "map12m"  , 0 },
	{ "map13m"  , 0 },
	{ "map14m"  , 0 },
	{ "map15m"  , 0 },
	{ "map16m"  , 0 },
	{ "map17m"  , 0 },
	{ "map18m"  , 0 },
	{ "map19m"  , 0 },
	{ "map20m"  , 0 },
	{ "map21m"  , 0 },
	{ "map22m"  , 0 },
	{ "map23m"  , 0 },
	{ "map24m"  , 0 },
	{ "map25m"  , 0 },
	{ "map26m"  , 0 },
	{ "map27m"  , 0 },
	{ "map28m"  , 0 },
	{ "map29m"  , 0 },
	{ "map30m"  , 0 },
	{ "map31m"  , 0 },
	{ "map32m"  , 0 },
	{ "map33m"  , 0 },
	{ "map34m"  , 0 },
	{ "map35m"  , 0 },
	{ "map36m"  , 0 },
	{ "map37m"  , 0 },
	{ "map38m"  , 0 },
	{ "map39m"  , 0 },
	{ "map40m"  , 0 },
	{ "map41m"  , 0 },
	{ "map42m"  , 0 },
	{ "map43m"  , 0 },
	{ "map44m"  , 0 },
	{ "map45m"  , 0 },
	{ "map46m"  , 0 },
	{ "map47m"  , 0 },
	{ "map48m"  , 0 },
	{ "map49m"  , 0 },
	{ "map50m"  , 0 },
	{ "map51m"  , 0 },
	{ "map52m"  , 0 },
	{ "map53m"  , 0 },
	{ "map54m"  , 0 },
	{ "map55m"  , 0 },
	{ "map56m"  , 0 },
	{ "map57m"  , 0 },
	{ "map58m"  , 0 },
	{ "map59m"  , 0 },
	{ "map60m"  , 0 }, // Normal music for maps 60-66 Graue 12-03-2003
	                   // Special stages will use O_MAP60M/D_MAP60M and level headers
	{ "map61m"  , 0 },
	{ "map62m"  , 0 },
	{ "map63m"  , 0 },
	{ "map64m"  , 0 },
	{ "map65m"  , 0 },
	{ "map66m"  , 0 },
	{ "map67m"  , 0 },
	{ "map68m"  , 0 },
	{ "map69m"  , 0 },
	{ "map70m"  , 0 },
	{ "map71m"  , 0 },
	{ "map72m"  , 0 },
	{ "map73m"  , 0 },
	{ "map74m"  , 0 },
	{ "map75m"  , 0 },
	{ "map76m"  , 0 },
	{ "map77m"  , 0 },
	{ "map78m"  , 0 },
	{ "map79m"  , 0 },
	{ "map80m"  , 0 },
	{ "map81m"  , 0 },
	{ "map82m"  , 0 },
	{ "map83m"  , 0 },
	{ "map84m"  , 0 },
	{ "map85m"  , 0 },
	{ "map86m"  , 0 },
	{ "map87m"  , 0 },
	{ "map88m"  , 0 },
	{ "map89m"  , 0 },
	{ "map90m"  , 0 },
	{ "map91m"  , 0 },
	{ "map92m"  , 0 },
	{ "map93m"  , 0 },
	{ "map94m"  , 0 },
	{ "map95m"  , 0 },
	{ "map96m"  , 0 },
	{ "map97m"  , 0 },
	{ "map98m"  , 0 },
	{ "map99m"  , 0 },
	{ "mapa0m"  , 0 },
	{ "mapa1m"  , 0 },
	{ "mapa2m"  , 0 },
	{ "mapa3m"  , 0 },
	{ "mapa4m"  , 0 },
	{ "mapa5m"  , 0 },
	{ "mapa6m"  , 0 },
	{ "mapa7m"  , 0 },
	{ "mapa8m"  , 0 },
	{ "mapa9m"  , 0 },
	{ "mapaam"  , 0 },
	{ "mapabm"  , 0 },
	{ "mapacm"  , 0 },
	{ "mapadm"  , 0 },
	{ "mapaem"  , 0 },
	{ "mapafm"  , 0 },
	{ "mapagm"  , 0 },
	{ "mapahm"  , 0 },
	{ "mapaim"  , 0 },
	{ "mapajm"  , 0 },
	{ "mapakm"  , 0 },
	{ "mapalm"  , 0 },
	{ "mapamm"  , 0 },
	{ "mapanm"  , 0 },
	{ "mapaom"  , 0 },
	{ "mapapm"  , 0 },
	{ "mapaqm"  , 0 },
	{ "maparm"  , 0 },
	{ "mapasm"  , 0 },
	{ "mapatm"  , 0 },
	{ "mapaum"  , 0 },
	{ "mapavm"  , 0 },
	{ "mapawm"  , 0 },
	{ "mapaxm"  , 0 },
	{ "mapaym"  , 0 },
	{ "mapazm"  , 0 },
	{ "mapb0m"  , 0 },
	{ "mapb1m"  , 0 },
	{ "mapb2m"  , 0 },
	{ "mapb3m"  , 0 },
	{ "mapb4m"  , 0 },
	{ "mapb5m"  , 0 },
	{ "mapb6m"  , 0 },
	{ "mapb7m"  , 0 },
	{ "mapb8m"  , 0 },
	{ "mapb9m"  , 0 },
	{ "mapbam"  , 0 },
	{ "mapbbm"  , 0 },
	{ "mapbcm"  , 0 },
	{ "mapbdm"  , 0 },
	{ "mapbem"  , 0 },
	{ "mapbfm"  , 0 },
	{ "mapbgm"  , 0 },
	{ "mapbhm"  , 0 },
	{ "mapbim"  , 0 },
	{ "mapbjm"  , 0 },
	{ "mapbkm"  , 0 },
	{ "mapblm"  , 0 },
	{ "mapbmm"  , 0 },
	{ "mapbnm"  , 0 },
	{ "mapbom"  , 0 },
	{ "mapbpm"  , 0 },
	{ "mapbqm"  , 0 },
	{ "mapbrm"  , 0 },
	{ "mapbsm"  , 0 },
	{ "mapbtm"  , 0 },
	{ "mapbum"  , 0 },
	{ "mapbvm"  , 0 },
	{ "mapbwm"  , 0 },
	{ "mapbxm"  , 0 },
	{ "mapbym"  , 0 },
	{ "mapbzm"  , 0 },
	{ "mapc0m"  , 0 },
	{ "mapc1m"  , 0 },
	{ "mapc2m"  , 0 },
	{ "mapc3m"  , 0 },
	{ "mapc4m"  , 0 },
	{ "mapc5m"  , 0 },
	{ "mapc6m"  , 0 },
	{ "mapc7m"  , 0 },
	{ "mapc8m"  , 0 },
	{ "mapc9m"  , 0 },
	{ "mapcam"  , 0 },
	{ "mapcbm"  , 0 },
	{ "mapccm"  , 0 },
	{ "mapcdm"  , 0 },
	{ "mapcem"  , 0 },
	{ "mapcfm"  , 0 },
	{ "mapcgm"  , 0 },
	{ "mapchm"  , 0 },
	{ "mapcim"  , 0 },
	{ "mapcjm"  , 0 },
	{ "mapckm"  , 0 },
	{ "mapclm"  , 0 },
	{ "mapcmm"  , 0 },
	{ "mapcnm"  , 0 },
	{ "mapcom"  , 0 },
	{ "mapcpm"  , 0 },
	{ "mapcqm"  , 0 },
	{ "mapcrm"  , 0 },
	{ "mapcsm"  , 0 },
	{ "mapctm"  , 0 },
	{ "mapcum"  , 0 },
	{ "mapcvm"  , 0 },
	{ "mapcwm"  , 0 },
	{ "mapcxm"  , 0 },
	{ "mapcym"  , 0 },
	{ "mapczm"  , 0 },
	{ "mapd0m"  , 0 },
	{ "mapd1m"  , 0 },
	{ "mapd2m"  , 0 },
	{ "mapd3m"  , 0 },
	{ "mapd4m"  , 0 },
	{ "mapd5m"  , 0 },
	{ "mapd6m"  , 0 },
	{ "mapd7m"  , 0 },
	{ "mapd8m"  , 0 },
	{ "mapd9m"  , 0 },
	{ "mapdam"  , 0 },
	{ "mapdbm"  , 0 },
	{ "mapdcm"  , 0 },
	{ "mapddm"  , 0 },
	{ "mapdem"  , 0 },
	{ "mapdfm"  , 0 },
	{ "mapdgm"  , 0 },
	{ "mapdhm"  , 0 },
	{ "mapdim"  , 0 },
	{ "mapdjm"  , 0 },
	{ "mapdkm"  , 0 },
	{ "mapdlm"  , 0 },
	{ "mapdmm"  , 0 },
	{ "mapdnm"  , 0 },
	{ "mapdom"  , 0 },
	{ "mapdpm"  , 0 },
	{ "mapdqm"  , 0 },
	{ "mapdrm"  , 0 },
	{ "mapdsm"  , 0 },
	{ "mapdtm"  , 0 },
	{ "mapdum"  , 0 },
	{ "mapdvm"  , 0 },
	{ "mapdwm"  , 0 },
	{ "mapdxm"  , 0 },
	{ "mapdym"  , 0 },
	{ "mapdzm"  , 0 },
	{ "mape0m"  , 0 },
	{ "mape1m"  , 0 },
	{ "mape2m"  , 0 },
	{ "mape3m"  , 0 },
	{ "mape4m"  , 0 },
	{ "mape5m"  , 0 },
	{ "mape6m"  , 0 },
	{ "mape7m"  , 0 },
	{ "mape8m"  , 0 },
	{ "mape9m"  , 0 },
	{ "mapeam"  , 0 },
	{ "mapebm"  , 0 },
	{ "mapecm"  , 0 },
	{ "mapedm"  , 0 },
	{ "mapeem"  , 0 },
	{ "mapefm"  , 0 },
	{ "mapegm"  , 0 },
	{ "mapehm"  , 0 },
	{ "mapeim"  , 0 },
	{ "mapejm"  , 0 },
	{ "mapekm"  , 0 },
	{ "mapelm"  , 0 },
	{ "mapemm"  , 0 },
	{ "mapenm"  , 0 },
	{ "mapeom"  , 0 },
	{ "mapepm"  , 0 },
	{ "mapeqm"  , 0 },
	{ "maperm"  , 0 },
	{ "mapesm"  , 0 },
	{ "mapetm"  , 0 },
	{ "mapeum"  , 0 },
	{ "mapevm"  , 0 },
	{ "mapewm"  , 0 },
	{ "mapexm"  , 0 },
	{ "mapeym"  , 0 },
	{ "mapezm"  , 0 },
	{ "mapf0m"  , 0 },
	{ "mapf1m"  , 0 },
	{ "mapf2m"  , 0 },
	{ "mapf3m"  , 0 },
	{ "mapf4m"  , 0 },
	{ "mapf5m"  , 0 },
	{ "mapf6m"  , 0 },
	{ "mapf7m"  , 0 },
	{ "mapf8m"  , 0 },
	{ "mapf9m"  , 0 },
	{ "mapfam"  , 0 },
	{ "mapfbm"  , 0 },
	{ "mapfcm"  , 0 },
	{ "mapfdm"  , 0 },
	{ "mapfem"  , 0 },
	{ "mapffm"  , 0 },
	{ "mapfgm"  , 0 },
	{ "mapfhm"  , 0 },
	{ "mapfim"  , 0 },
	{ "mapfjm"  , 0 },
	{ "mapfkm"  , 0 },
	{ "mapflm"  , 0 },
	{ "mapfmm"  , 0 },
	{ "mapfnm"  , 0 },
	{ "mapfom"  , 0 },
	{ "mapfpm"  , 0 },
	{ "mapfqm"  , 0 },
	{ "mapfrm"  , 0 },
	{ "mapfsm"  , 0 },
	{ "mapftm"  , 0 },
	{ "mapfum"  , 0 },
	{ "mapfvm"  , 0 },
	{ "mapfwm"  , 0 },
	{ "mapfxm"  , 0 },
	{ "mapfym"  , 0 },
	{ "mapfzm"  , 0 },
	{ "mapg0m"  , 0 },
	{ "mapg1m"  , 0 },
	{ "mapg2m"  , 0 },
	{ "mapg3m"  , 0 },
	{ "mapg4m"  , 0 },
	{ "mapg5m"  , 0 },
	{ "mapg6m"  , 0 },
	{ "mapg7m"  , 0 },
	{ "mapg8m"  , 0 },
	{ "mapg9m"  , 0 },
	{ "mapgam"  , 0 },
	{ "mapgbm"  , 0 },
	{ "mapgcm"  , 0 },
	{ "mapgdm"  , 0 },
	{ "mapgem"  , 0 },
	{ "mapgfm"  , 0 },
	{ "mapggm"  , 0 },
	{ "mapghm"  , 0 },
	{ "mapgim"  , 0 },
	{ "mapgjm"  , 0 },
	{ "mapgkm"  , 0 },
	{ "mapglm"  , 0 },
	{ "mapgmm"  , 0 },
	{ "mapgnm"  , 0 },
	{ "mapgom"  , 0 },
	{ "mapgpm"  , 0 },
	{ "mapgqm"  , 0 },
	{ "mapgrm"  , 0 },
	{ "mapgsm"  , 0 },
	{ "mapgtm"  , 0 },
	{ "mapgum"  , 0 },
	{ "mapgvm"  , 0 },
	{ "mapgwm"  , 0 },
	{ "mapgxm"  , 0 },
	{ "mapgym"  , 0 },
	{ "mapgzm"  , 0 },
	{ "maph0m"  , 0 },
	{ "maph1m"  , 0 },
	{ "maph2m"  , 0 },
	{ "maph3m"  , 0 },
	{ "maph4m"  , 0 },
	{ "maph5m"  , 0 },
	{ "maph6m"  , 0 },
	{ "maph7m"  , 0 },
	{ "maph8m"  , 0 },
	{ "maph9m"  , 0 },
	{ "mapham"  , 0 },
	{ "maphbm"  , 0 },
	{ "maphcm"  , 0 },
	{ "maphdm"  , 0 },
	{ "maphem"  , 0 },
	{ "maphfm"  , 0 },
	{ "maphgm"  , 0 },
	{ "maphhm"  , 0 },
	{ "maphim"  , 0 },
	{ "maphjm"  , 0 },
	{ "maphkm"  , 0 },
	{ "maphlm"  , 0 },
	{ "maphmm"  , 0 },
	{ "maphnm"  , 0 },
	{ "maphom"  , 0 },
	{ "maphpm"  , 0 },
	{ "maphqm"  , 0 },
	{ "maphrm"  , 0 },
	{ "maphsm"  , 0 },
	{ "maphtm"  , 0 },
	{ "maphum"  , 0 },
	{ "maphvm"  , 0 },
	{ "maphwm"  , 0 },
	{ "maphxm"  , 0 },
	{ "maphym"  , 0 },
	{ "maphzm"  , 0 },
	{ "mapi0m"  , 0 },
	{ "mapi1m"  , 0 },
	{ "mapi2m"  , 0 },
	{ "mapi3m"  , 0 },
	{ "mapi4m"  , 0 },
	{ "mapi5m"  , 0 },
	{ "mapi6m"  , 0 },
	{ "mapi7m"  , 0 },
	{ "mapi8m"  , 0 },
	{ "mapi9m"  , 0 },
	{ "mapiam"  , 0 },
	{ "mapibm"  , 0 },
	{ "mapicm"  , 0 },
	{ "mapidm"  , 0 },
	{ "mapiem"  , 0 },
	{ "mapifm"  , 0 },
	{ "mapigm"  , 0 },
	{ "mapihm"  , 0 },
	{ "mapiim"  , 0 },
	{ "mapijm"  , 0 },
	{ "mapikm"  , 0 },
	{ "mapilm"  , 0 },
	{ "mapimm"  , 0 },
	{ "mapinm"  , 0 },
	{ "mapiom"  , 0 },
	{ "mapipm"  , 0 },
	{ "mapiqm"  , 0 },
	{ "mapirm"  , 0 },
	{ "mapism"  , 0 },
	{ "mapitm"  , 0 },
	{ "mapium"  , 0 },
	{ "mapivm"  , 0 },
	{ "mapiwm"  , 0 },
	{ "mapixm"  , 0 },
	{ "mapiym"  , 0 },
	{ "mapizm"  , 0 },
	{ "mapj0m"  , 0 },
	{ "mapj1m"  , 0 },
	{ "mapj2m"  , 0 },
	{ "mapj3m"  , 0 },
	{ "mapj4m"  , 0 },
	{ "mapj5m"  , 0 },
	{ "mapj6m"  , 0 },
	{ "mapj7m"  , 0 },
	{ "mapj8m"  , 0 },
	{ "mapj9m"  , 0 },
	{ "mapjam"  , 0 },
	{ "mapjbm"  , 0 },
	{ "mapjcm"  , 0 },
	{ "mapjdm"  , 0 },
	{ "mapjem"  , 0 },
	{ "mapjfm"  , 0 },
	{ "mapjgm"  , 0 },
	{ "mapjhm"  , 0 },
	{ "mapjim"  , 0 },
	{ "mapjjm"  , 0 },
	{ "mapjkm"  , 0 },
	{ "mapjlm"  , 0 },
	{ "mapjmm"  , 0 },
	{ "mapjnm"  , 0 },
	{ "mapjom"  , 0 },
	{ "mapjpm"  , 0 },
	{ "mapjqm"  , 0 },
	{ "mapjrm"  , 0 },
	{ "mapjsm"  , 0 },
	{ "mapjtm"  , 0 },
	{ "mapjum"  , 0 },
	{ "mapjvm"  , 0 },
	{ "mapjwm"  , 0 },
	{ "mapjxm"  , 0 },
	{ "mapjym"  , 0 },
	{ "mapjzm"  , 0 },
	{ "mapk0m"  , 0 },
	{ "mapk1m"  , 0 },
	{ "mapk2m"  , 0 },
	{ "mapk3m"  , 0 },
	{ "mapk4m"  , 0 },
	{ "mapk5m"  , 0 },
	{ "mapk6m"  , 0 },
	{ "mapk7m"  , 0 },
	{ "mapk8m"  , 0 },
	{ "mapk9m"  , 0 },
	{ "mapkam"  , 0 },
	{ "mapkbm"  , 0 },
	{ "mapkcm"  , 0 },
	{ "mapkdm"  , 0 },
	{ "mapkem"  , 0 },
	{ "mapkfm"  , 0 },
	{ "mapkgm"  , 0 },
	{ "mapkhm"  , 0 },
	{ "mapkim"  , 0 },
	{ "mapkjm"  , 0 },
	{ "mapkkm"  , 0 },
	{ "mapklm"  , 0 },
	{ "mapkmm"  , 0 },
	{ "mapknm"  , 0 },
	{ "mapkom"  , 0 },
	{ "mapkpm"  , 0 },
	{ "mapkqm"  , 0 },
	{ "mapkrm"  , 0 },
	{ "mapksm"  , 0 },
	{ "mapktm"  , 0 },
	{ "mapkum"  , 0 },
	{ "mapkvm"  , 0 },
	{ "mapkwm"  , 0 },
	{ "mapkxm"  , 0 },
	{ "mapkym"  , 0 },
	{ "mapkzm"  , 0 },
	{ "mapl0m"  , 0 },
	{ "mapl1m"  , 0 },
	{ "mapl2m"  , 0 },
	{ "mapl3m"  , 0 },
	{ "mapl4m"  , 0 },
	{ "mapl5m"  , 0 },
	{ "mapl6m"  , 0 },
	{ "mapl7m"  , 0 },
	{ "mapl8m"  , 0 },
	{ "mapl9m"  , 0 },
	{ "maplam"  , 0 },
	{ "maplbm"  , 0 },
	{ "maplcm"  , 0 },
	{ "mapldm"  , 0 },
	{ "maplem"  , 0 },
	{ "maplfm"  , 0 },
	{ "maplgm"  , 0 },
	{ "maplhm"  , 0 },
	{ "maplim"  , 0 },
	{ "mapljm"  , 0 },
	{ "maplkm"  , 0 },
	{ "mapllm"  , 0 },
	{ "maplmm"  , 0 },
	{ "maplnm"  , 0 },
	{ "maplom"  , 0 },
	{ "maplpm"  , 0 },
	{ "maplqm"  , 0 },
	{ "maplrm"  , 0 },
	{ "maplsm"  , 0 },
	{ "mapltm"  , 0 },
	{ "maplum"  , 0 },
	{ "maplvm"  , 0 },
	{ "maplwm"  , 0 },
	{ "maplxm"  , 0 },
	{ "maplym"  , 0 },
	{ "maplzm"  , 0 },
	{ "mapm0m"  , 0 },
	{ "mapm1m"  , 0 },
	{ "mapm2m"  , 0 },
	{ "mapm3m"  , 0 },
	{ "mapm4m"  , 0 },
	{ "mapm5m"  , 0 },
	{ "mapm6m"  , 0 },
	{ "mapm7m"  , 0 },
	{ "mapm8m"  , 0 },
	{ "mapm9m"  , 0 },
	{ "mapmam"  , 0 },
	{ "mapmbm"  , 0 },
	{ "mapmcm"  , 0 },
	{ "mapmdm"  , 0 },
	{ "mapmem"  , 0 },
	{ "mapmfm"  , 0 },
	{ "mapmgm"  , 0 },
	{ "mapmhm"  , 0 },
	{ "mapmim"  , 0 },
	{ "mapmjm"  , 0 },
	{ "mapmkm"  , 0 },
	{ "mapmlm"  , 0 },
	{ "mapmmm"  , 0 },
	{ "mapmnm"  , 0 },
	{ "mapmom"  , 0 },
	{ "mapmpm"  , 0 },
	{ "mapmqm"  , 0 },
	{ "mapmrm"  , 0 },
	{ "mapmsm"  , 0 },
	{ "mapmtm"  , 0 },
	{ "mapmum"  , 0 },
	{ "mapmvm"  , 0 },
	{ "mapmwm"  , 0 },
	{ "mapmxm"  , 0 },
	{ "mapmym"  , 0 },
	{ "mapmzm"  , 0 },
	{ "mapn0m"  , 0 },
	{ "mapn1m"  , 0 },
	{ "mapn2m"  , 0 },
	{ "mapn3m"  , 0 },
	{ "mapn4m"  , 0 },
	{ "mapn5m"  , 0 },
	{ "mapn6m"  , 0 },
	{ "mapn7m"  , 0 },
	{ "mapn8m"  , 0 },
	{ "mapn9m"  , 0 },
	{ "mapnam"  , 0 },
	{ "mapnbm"  , 0 },
	{ "mapncm"  , 0 },
	{ "mapndm"  , 0 },
	{ "mapnem"  , 0 },
	{ "mapnfm"  , 0 },
	{ "mapngm"  , 0 },
	{ "mapnhm"  , 0 },
	{ "mapnim"  , 0 },
	{ "mapnjm"  , 0 },
	{ "mapnkm"  , 0 },
	{ "mapnlm"  , 0 },
	{ "mapnmm"  , 0 },
	{ "mapnnm"  , 0 },
	{ "mapnom"  , 0 },
	{ "mapnpm"  , 0 },
	{ "mapnqm"  , 0 },
	{ "mapnrm"  , 0 },
	{ "mapnsm"  , 0 },
	{ "mapntm"  , 0 },
	{ "mapnum"  , 0 },
	{ "mapnvm"  , 0 },
	{ "mapnwm"  , 0 },
	{ "mapnxm"  , 0 },
	{ "mapnym"  , 0 },
	{ "mapnzm"  , 0 },
	{ "mapo0m"  , 0 },
	{ "mapo1m"  , 0 },
	{ "mapo2m"  , 0 },
	{ "mapo3m"  , 0 },
	{ "mapo4m"  , 0 },
	{ "mapo5m"  , 0 },
	{ "mapo6m"  , 0 },
	{ "mapo7m"  , 0 },
	{ "mapo8m"  , 0 },
	{ "mapo9m"  , 0 },
	{ "mapoam"  , 0 },
	{ "mapobm"  , 0 },
	{ "mapocm"  , 0 },
	{ "mapodm"  , 0 },
	{ "mapoem"  , 0 },
	{ "mapofm"  , 0 },
	{ "mapogm"  , 0 },
	{ "mapohm"  , 0 },
	{ "mapoim"  , 0 },
	{ "mapojm"  , 0 },
	{ "mapokm"  , 0 },
	{ "mapolm"  , 0 },
	{ "mapomm"  , 0 },
	{ "maponm"  , 0 },
	{ "mapoom"  , 0 },
	{ "mapopm"  , 0 },
	{ "mapoqm"  , 0 },
	{ "maporm"  , 0 },
	{ "maposm"  , 0 },
	{ "mapotm"  , 0 },
	{ "mapoum"  , 0 },
	{ "mapovm"  , 0 },
	{ "mapowm"  , 0 },
	{ "mapoxm"  , 0 },
	{ "mapoym"  , 0 },
	{ "mapozm"  , 0 },
	{ "mapp0m"  , 0 },
	{ "mapp1m"  , 0 },
	{ "mapp2m"  , 0 },
	{ "mapp3m"  , 0 },
	{ "mapp4m"  , 0 },
	{ "mapp5m"  , 0 },
	{ "mapp6m"  , 0 },
	{ "mapp7m"  , 0 },
	{ "mapp8m"  , 0 },
	{ "mapp9m"  , 0 },
	{ "mappam"  , 0 },
	{ "mappbm"  , 0 },
	{ "mappcm"  , 0 },
	{ "mappdm"  , 0 },
	{ "mappem"  , 0 },
	{ "mappfm"  , 0 },
	{ "mappgm"  , 0 },
	{ "mapphm"  , 0 },
	{ "mappim"  , 0 },
	{ "mappjm"  , 0 },
	{ "mappkm"  , 0 },
	{ "mapplm"  , 0 },
	{ "mappmm"  , 0 },
	{ "mappnm"  , 0 },
	{ "mappom"  , 0 },
	{ "mapppm"  , 0 },
	{ "mappqm"  , 0 },
	{ "mapprm"  , 0 },
	{ "mappsm"  , 0 },
	{ "mapptm"  , 0 },
	{ "mappum"  , 0 },
	{ "mappvm"  , 0 },
	{ "mappwm"  , 0 },
	{ "mappxm"  , 0 },
	{ "mappym"  , 0 },
	{ "mappzm"  , 0 },
	{ "mapq0m"  , 0 },
	{ "mapq1m"  , 0 },
	{ "mapq2m"  , 0 },
	{ "mapq3m"  , 0 },
	{ "mapq4m"  , 0 },
	{ "mapq5m"  , 0 },
	{ "mapq6m"  , 0 },
	{ "mapq7m"  , 0 },
	{ "mapq8m"  , 0 },
	{ "mapq9m"  , 0 },
	{ "mapqam"  , 0 },
	{ "mapqbm"  , 0 },
	{ "mapqcm"  , 0 },
	{ "mapqdm"  , 0 },
	{ "mapqem"  , 0 },
	{ "mapqfm"  , 0 },
	{ "mapqgm"  , 0 },
	{ "mapqhm"  , 0 },
	{ "mapqim"  , 0 },
	{ "mapqjm"  , 0 },
	{ "mapqkm"  , 0 },
	{ "mapqlm"  , 0 },
	{ "mapqmm"  , 0 },
	{ "mapqnm"  , 0 },
	{ "mapqom"  , 0 },
	{ "mapqpm"  , 0 },
	{ "mapqqm"  , 0 },
	{ "mapqrm"  , 0 },
	{ "mapqsm"  , 0 },
	{ "mapqtm"  , 0 },
	{ "mapqum"  , 0 },
	{ "mapqvm"  , 0 },
	{ "mapqwm"  , 0 },
	{ "mapqxm"  , 0 },
	{ "mapqym"  , 0 },
	{ "mapqzm"  , 0 },
	{ "mapr0m"  , 0 },
	{ "mapr1m"  , 0 },
	{ "mapr2m"  , 0 },
	{ "mapr3m"  , 0 },
	{ "mapr4m"  , 0 },
	{ "mapr5m"  , 0 },
	{ "mapr6m"  , 0 },
	{ "mapr7m"  , 0 },
	{ "mapr8m"  , 0 },
	{ "mapr9m"  , 0 },
	{ "mapram"  , 0 },
	{ "maprbm"  , 0 },
	{ "maprcm"  , 0 },
	{ "maprdm"  , 0 },
	{ "maprem"  , 0 },
	{ "maprfm"  , 0 },
	{ "maprgm"  , 0 },
	{ "maprhm"  , 0 },
	{ "maprim"  , 0 },
	{ "maprjm"  , 0 },
	{ "maprkm"  , 0 },
	{ "maprlm"  , 0 },
	{ "maprmm"  , 0 },
	{ "maprnm"  , 0 },
	{ "maprom"  , 0 },
	{ "maprpm"  , 0 },
	{ "maprqm"  , 0 },
	{ "maprrm"  , 0 },
	{ "maprsm"  , 0 },
	{ "maprtm"  , 0 },
	{ "maprum"  , 0 },
	{ "maprvm"  , 0 },
	{ "maprwm"  , 0 },
	{ "maprxm"  , 0 },
	{ "maprym"  , 0 },
	{ "maprzm"  , 0 },
	{ "maps0m"  , 0 },
	{ "maps1m"  , 0 },
	{ "maps2m"  , 0 },
	{ "maps3m"  , 0 },
	{ "maps4m"  , 0 },
	{ "maps5m"  , 0 },
	{ "maps6m"  , 0 },
	{ "maps7m"  , 0 },
	{ "maps8m"  , 0 },
	{ "maps9m"  , 0 },
	{ "mapsam"  , 0 },
	{ "mapsbm"  , 0 },
	{ "mapscm"  , 0 },
	{ "mapsdm"  , 0 },
	{ "mapsem"  , 0 },
	{ "mapsfm"  , 0 },
	{ "mapsgm"  , 0 },
	{ "mapshm"  , 0 },
	{ "mapsim"  , 0 },
	{ "mapsjm"  , 0 },
	{ "mapskm"  , 0 },
	{ "mapslm"  , 0 },
	{ "mapsmm"  , 0 },
	{ "mapsnm"  , 0 },
	{ "mapsom"  , 0 },
	{ "mapspm"  , 0 },
	{ "mapsqm"  , 0 },
	{ "mapsrm"  , 0 },
	{ "mapssm"  , 0 },
	{ "mapstm"  , 0 },
	{ "mapsum"  , 0 },
	{ "mapsvm"  , 0 },
	{ "mapswm"  , 0 },
	{ "mapsxm"  , 0 },
	{ "mapsym"  , 0 },
	{ "mapszm"  , 0 },
	{ "mapt0m"  , 0 },
	{ "mapt1m"  , 0 },
	{ "mapt2m"  , 0 },
	{ "mapt3m"  , 0 },
	{ "mapt4m"  , 0 },
	{ "mapt5m"  , 0 },
	{ "mapt6m"  , 0 },
	{ "mapt7m"  , 0 },
	{ "mapt8m"  , 0 },
	{ "mapt9m"  , 0 },
	{ "maptam"  , 0 },
	{ "maptbm"  , 0 },
	{ "maptcm"  , 0 },
	{ "maptdm"  , 0 },
	{ "maptem"  , 0 },
	{ "maptfm"  , 0 },
	{ "maptgm"  , 0 },
	{ "mapthm"  , 0 },
	{ "maptim"  , 0 },
	{ "maptjm"  , 0 },
	{ "maptkm"  , 0 },
	{ "maptlm"  , 0 },
	{ "maptmm"  , 0 },
	{ "maptnm"  , 0 },
	{ "maptom"  , 0 },
	{ "maptpm"  , 0 },
	{ "maptqm"  , 0 },
	{ "maptrm"  , 0 },
	{ "maptsm"  , 0 },
	{ "mapttm"  , 0 },
	{ "maptum"  , 0 },
	{ "maptvm"  , 0 },
	{ "maptwm"  , 0 },
	{ "maptxm"  , 0 },
	{ "maptym"  , 0 },
	{ "maptzm"  , 0 },
	{ "mapu0m"  , 0 },
	{ "mapu1m"  , 0 },
	{ "mapu2m"  , 0 },
	{ "mapu3m"  , 0 },
	{ "mapu4m"  , 0 },
	{ "mapu5m"  , 0 },
	{ "mapu6m"  , 0 },
	{ "mapu7m"  , 0 },
	{ "mapu8m"  , 0 },
	{ "mapu9m"  , 0 },
	{ "mapuam"  , 0 },
	{ "mapubm"  , 0 },
	{ "mapucm"  , 0 },
	{ "mapudm"  , 0 },
	{ "mapuem"  , 0 },
	{ "mapufm"  , 0 },
	{ "mapugm"  , 0 },
	{ "mapuhm"  , 0 },
	{ "mapuim"  , 0 },
	{ "mapujm"  , 0 },
	{ "mapukm"  , 0 },
	{ "mapulm"  , 0 },
	{ "mapumm"  , 0 },
	{ "mapunm"  , 0 },
	{ "mapuom"  , 0 },
	{ "mapupm"  , 0 },
	{ "mapuqm"  , 0 },
	{ "mapurm"  , 0 },
	{ "mapusm"  , 0 },
	{ "maputm"  , 0 },
	{ "mapuum"  , 0 },
	{ "mapuvm"  , 0 },
	{ "mapuwm"  , 0 },
	{ "mapuxm"  , 0 },
	{ "mapuym"  , 0 },
	{ "mapuzm"  , 0 },
	{ "mapv0m"  , 0 },
	{ "mapv1m"  , 0 },
	{ "mapv2m"  , 0 },
	{ "mapv3m"  , 0 },
	{ "mapv4m"  , 0 },
	{ "mapv5m"  , 0 },
	{ "mapv6m"  , 0 },
	{ "mapv7m"  , 0 },
	{ "mapv8m"  , 0 },
	{ "mapv9m"  , 0 },
	{ "mapvam"  , 0 },
	{ "mapvbm"  , 0 },
	{ "mapvcm"  , 0 },
	{ "mapvdm"  , 0 },
	{ "mapvem"  , 0 },
	{ "mapvfm"  , 0 },
	{ "mapvgm"  , 0 },
	{ "mapvhm"  , 0 },
	{ "mapvim"  , 0 },
	{ "mapvjm"  , 0 },
	{ "mapvkm"  , 0 },
	{ "mapvlm"  , 0 },
	{ "mapvmm"  , 0 },
	{ "mapvnm"  , 0 },
	{ "mapvom"  , 0 },
	{ "mapvpm"  , 0 },
	{ "mapvqm"  , 0 },
	{ "mapvrm"  , 0 },
	{ "mapvsm"  , 0 },
	{ "mapvtm"  , 0 },
	{ "mapvum"  , 0 },
	{ "mapvvm"  , 0 },
	{ "mapvwm"  , 0 },
	{ "mapvxm"  , 0 },
	{ "mapvym"  , 0 },
	{ "mapvzm"  , 0 },
	{ "mapw0m"  , 0 },
	{ "mapw1m"  , 0 },
	{ "mapw2m"  , 0 },
	{ "mapw3m"  , 0 },
	{ "mapw4m"  , 0 },
	{ "mapw5m"  , 0 },
	{ "mapw6m"  , 0 },
	{ "mapw7m"  , 0 },
	{ "mapw8m"  , 0 },
	{ "mapw9m"  , 0 },
	{ "mapwam"  , 0 },
	{ "mapwbm"  , 0 },
	{ "mapwcm"  , 0 },
	{ "mapwdm"  , 0 },
	{ "mapwem"  , 0 },
	{ "mapwfm"  , 0 },
	{ "mapwgm"  , 0 },
	{ "mapwhm"  , 0 },
	{ "mapwim"  , 0 },
	{ "mapwjm"  , 0 },
	{ "mapwkm"  , 0 },
	{ "mapwlm"  , 0 },
	{ "mapwmm"  , 0 },
	{ "mapwnm"  , 0 },
	{ "mapwom"  , 0 },
	{ "mapwpm"  , 0 },
	{ "mapwqm"  , 0 },
	{ "mapwrm"  , 0 },
	{ "mapwsm"  , 0 },
	{ "mapwtm"  , 0 },
	{ "mapwum"  , 0 },
	{ "mapwvm"  , 0 },
	{ "mapwwm"  , 0 },
	{ "mapwxm"  , 0 },
	{ "mapwym"  , 0 },
	{ "mapwzm"  , 0 },
	{ "mapx0m"  , 0 },
	{ "mapx1m"  , 0 },
	{ "mapx2m"  , 0 },
	{ "mapx3m"  , 0 },
	{ "mapx4m"  , 0 },
	{ "mapx5m"  , 0 },
	{ "mapx6m"  , 0 },
	{ "mapx7m"  , 0 },
	{ "mapx8m"  , 0 },
	{ "mapx9m"  , 0 },
	{ "mapxam"  , 0 },
	{ "mapxbm"  , 0 },
	{ "mapxcm"  , 0 },
	{ "mapxdm"  , 0 },
	{ "mapxem"  , 0 },
	{ "mapxfm"  , 0 },
	{ "mapxgm"  , 0 },
	{ "mapxhm"  , 0 },
	{ "mapxim"  , 0 },
	{ "mapxjm"  , 0 },
	{ "mapxkm"  , 0 },
	{ "mapxlm"  , 0 },
	{ "mapxmm"  , 0 },
	{ "mapxnm"  , 0 },
	{ "mapxom"  , 0 },
	{ "mapxpm"  , 0 },
	{ "mapxqm"  , 0 },
	{ "mapxrm"  , 0 },
	{ "mapxsm"  , 0 },
	{ "mapxtm"  , 0 },
	{ "mapxum"  , 0 },
	{ "mapxvm"  , 0 },
	{ "mapxwm"  , 0 },
	{ "mapxxm"  , 0 },
	{ "mapxym"  , 0 },
	{ "mapxzm"  , 0 },
	{ "mapy0m"  , 0 },
	{ "mapy1m"  , 0 },
	{ "mapy2m"  , 0 },
	{ "mapy3m"  , 0 },
	{ "mapy4m"  , 0 },
	{ "mapy5m"  , 0 },
	{ "mapy6m"  , 0 },
	{ "mapy7m"  , 0 },
	{ "mapy8m"  , 0 },
	{ "mapy9m"  , 0 },
	{ "mapyam"  , 0 },
	{ "mapybm"  , 0 },
	{ "mapycm"  , 0 },
	{ "mapydm"  , 0 },
	{ "mapyem"  , 0 },
	{ "mapyfm"  , 0 },
	{ "mapygm"  , 0 },
	{ "mapyhm"  , 0 },
	{ "mapyim"  , 0 },
	{ "mapyjm"  , 0 },
	{ "mapykm"  , 0 },
	{ "mapylm"  , 0 },
	{ "mapymm"  , 0 },
	{ "mapynm"  , 0 },
	{ "mapyom"  , 0 },
	{ "mapypm"  , 0 },
	{ "mapyqm"  , 0 },
	{ "mapyrm"  , 0 },
	{ "mapysm"  , 0 },
	{ "mapytm"  , 0 },
	{ "mapyum"  , 0 },
	{ "mapyvm"  , 0 },
	{ "mapywm"  , 0 },
	{ "mapyxm"  , 0 },
	{ "mapyym"  , 0 },
	{ "mapyzm"  , 0 },
	{ "mapz0m"  , 0 },
	{ "mapz1m"  , 0 },
	{ "mapz2m"  , 0 },
	{ "mapz3m"  , 0 },
	{ "mapz4m"  , 0 },
	{ "mapz5m"  , 0 },
	{ "mapz6m"  , 0 },
	{ "mapz7m"  , 0 },
	{ "mapz8m"  , 0 },
	{ "mapz9m"  , 0 },
	{ "mapzam"  , 0 },
	{ "mapzbm"  , 0 },
	{ "mapzcm"  , 0 },
	{ "mapzdm"  , 0 },
	{ "mapzem"  , 0 },
	{ "mapzfm"  , 0 },
	{ "mapzgm"  , 0 },
	{ "mapzhm"  , 0 },
	{ "mapzim"  , 0 },
	{ "mapzjm"  , 0 },
	{ "mapzkm"  , 0 },
	{ "mapzlm"  , 0 },
	{ "mapzmm"  , 0 },
	{ "mapznm"  , 0 },
	{ "mapzom"  , 0 },
	{ "mapzpm"  , 0 },
	{ "mapzqm"  , 0 },
	{ "mapzrm"  , 0 },
	{ "mapzsm"  , 0 },
	{ "mapztm"  , 0 },
	{ "mapzum"  , 0 },
	{ "mapzvm"  , 0 },
	{ "mapzwm"  , 0 },
	{ "mapzxm"  , 0 },
	{ "mapzym"  , 0 },
	{ "mapzzm"  , 0 },

    { "titles"  , 0 }, // Moved it up Tails 01-06-2001
    { "read_m"  , 0 },
    { "lclear"  , 0 },
    { "invinc"  , 0 }, // invincibility Tails
	{ "shoes\0" , 0 }, // Super Sneakers Tails 06-21-2003
	{ "minvnc"  , 0 }, // Mario invincibility Tails
    { "drown\0" , 0 }, // drowning Tails 03-06-2000
    { "gmover"  , 0 }, // Tails 03-14-2000
    { "xtlife"  , 0 }, // Tails 03-14-2000
	{ "contsc"  , 0 }, // Continue screen Tails 06-04-2002
	{ "supers"  , 0 }, // Super Sonic Tails 06-04-2002
	{ "chrsel"  , 0 }, // Character Select Tails 07-04-2002
	{ "credit"  , 0 }, // Credits
};


//
// Information about all the sfx
//

sfxinfo_t S_sfx[NUMSFX] =
{

/*****
    Legacy doesn't use the PITCH variable, so now it is used to set
	which sound effects shouldn't be played together. If their pitch
	matches, the sound that wants to play will overwrite the other one
	that is already playing.

    42 is a magic pitch number which says that more than one sfx of this kind
	can be played on an origin at once.
*****/
  // S_sfx[0] needs to be a dummy for odd reasons.
//         singularity(U)        pitch      skinsound   (U) for UNUSED
//               |      priority(U) volume  |
//               |        |  link   |   data|
  { "none"     , false,   0, 0, -1, -1, 0, -1},

  { "menu1\0"   , true,  64, 0, -1, -1, 0, -1},
  { "shotgn"   , false,  64, 0, -1, -1, 0, -1},
  { "chchng"   , false,  120, 0, -1, -1, 0, -1},
  { "plasma"   , false,  64, 0, -1, -1, 0, -1},
  { "spin\0\0"  , false,  64, 0, -1, -1, 0, SKSSPIN},
  { "putput"   , false,  64, 0, -1, -1, 0, SKSPUTPUT}, // not as high a priority
  { "pudpud"   , false,  64, 0, -1, -1, 0, SKSPUDPUD},
  { "wtrdng"   , true,  120, 0, -1, -1, 0, -1}, // make sure you can hear the DING DING! Tails 03-08-2000
  { "strpst"   , true,  120, 0, -1, -1, 0, -1}, // Starpost Sound Tails 07-04-2002
  { "rlaunc"   , false,  64, 0, -1, -1, 0, -1},
  { "rxplod"   , false,  70, 0, -1, -1, 0, -1},
  { "dmpain",    false,  96, 0, -1, -1, 0, -1},
  { "lvpass"   , false,  70, 0, -1, -1, 0, -1},
  { "firxpl"   , false,  70, 0, -1, -1, 0, -1},
  { "pstart"   , false, 100, 0, -1, -1, 0, -1},
  { "pstop\0"  , false, 100, 0, -1, -1, 0, -1},
  { "doropn"   , false, 100, 0, -1, -1, 0, -1},
  { "dorcls"   , false, 100, 0, -1, -1, 0, -1},
  { "stnmov"   , false, 64, 0, -1, -1, 0, -1},
  { "swtchn"   , false,  78, 0, -1, -1, 0, -1},
  { "swtchx"   , false,  78, 0, -1, -1, 0, -1},
  { "pop\0\0\0" , false,  78, 0, -1, -1, 0, -1},
  { "itemup"   ,  true,  78, 0, -1, -1, 0, -1},
  { "wpnup"    ,  true,  78, 0, -1, -1, 0, -1},
  { "spring",	false,  96, 0, -1, -1, 0, -1},
  { "telept"   , false,  32, 0, -1, -1, 0, -1},
  { "thok\0\0"   , false,  32, 0, -1, -1, 0, SKSTHOK},
  { "cybdth"   , false,  32, 0, -1, -1, 0, -1},
  { "spndsh"  , false,  64, 0, 1, -1, 0, SKSSPNDSH},
  { "zoom\0\0"  , false,  120, 0, 1, -1, 0, SKSZOOM},
  { "tink\0\0" , false,  60, 0, -1, -1, 0, -1},
  { "bdopn\0"  , false, 100, 0, -1, -1, 0, -1},
  { "bdcls\0"  , false, 100, 0, -1, -1, 0, -1},
  { "shield"   , false,  60, 0, -1, -1, 0, -1},
  { "bkpoof"   , false,  70, 0, -1, -1, 0, -1},
  { "radio\0"  , false,  60, 0, -1, -1, 0, SKSRADIO},

  //added:22-02-98: sound when the player avatar jumps in air 'hmpf!'
  { "jump\0\0" , false,  60, 0, -1, -1, 0, SKSJUMP},
  { "gasp\0\0" , false,  64, 0, -1, -1, 0, SKSGASP},

  //added:09-08-98:test water sounds
  { "gloop\0"  , false,  60, 0, -1, -1, 0, -1},
  { "splash"   , false,  64, 0, -1, -1, 0, -1},
  { "floush"   , false,  64, 0, -1, -1, 0, -1},
  //Ambient Water Sounds Tails 06-10-2000
  { "amwtr1"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr2"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr3"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr4"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr5"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr6"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr7"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr8"   , false,  64, 0, -1, -1, 0, -1},
  { "amwtr9"   , false,  64, 0, -1, -1, 0, -1},
  { "splish"   , false,  64, 0, -1, -1, 0, -1}, // Splish Tails 12-08-2000
  { "wslap\0"   , false,  64, 0, -1, -1, 0, -1}, // Water Slap Tails 12-13-2000
  { "steam1"   , false,  64, 0, -1, -1, 0, -1}, // Tails 06-19-2001
  { "steam2"   , false,  64, 0, -1, -1, 0, -1}, // Tails 06-19-2001
  { "cgot\0\0"   , true,  120, 0, -1, -1, 0, -1}, // Got Emerald! Tails 09-02-2001
  { "crumbl"   , false,  127, 0, -1, -1, 0, -1}, // Platform Crumble Tails 03-16-2001

  // Ambient/Active lightning Tails 08-25-2002
  { "litng1"   , false,  126, 0, 42, -1, 0, -1},
  { "litng2"   , false,  126, 0, 42, -1, 0, -1},
  { "litng3"   , false,  126, 0, 42, -1, 0, -1},
  { "litng4"   , false,  126, 0, 42, -1, 0, -1},
  { "athun1"   , false,  126, 0, 42, -1, 0, -1},
  { "athun2"   , false,  126, 0, 42, -1, 0, -1},
  { "rainin"   , true,  127, 0, 43, -1, 0, -1},

  // Bubble pops Tails 08-25-2002
  { "bubbl1"   , false,  48, 0, -1, -1, 0, -1},
  { "bubbl2"   , false,  48, 0, -1, -1, 0, -1},
  { "bubbl3"   , false,  48, 0, -1, -1, 0, -1},
  { "bubbl4"   , false,  48, 0, -1, -1, 0, -1},
  { "bubbl5"   , false,  48, 0, -1, -1, 0, -1},

  // Teleporter mixup sound Tails 08-28-2002
  { "mixup\0"  , true,  127, 0, -1, -1, 0, -1},

  // Demo end talking Tails 09-01-2002
  { "annon1"  , true,  127, 0, -1, -1, 0, -1},
  { "annon2"  , true,  127, 0, -1, -1, 0, -1},
  { "annon3"  , true,  127, 0, -1, -1, 0, -1},
  { "annon4"  , true,  127, 0, -1, -1, 0, -1},
  { "annon5"  , true,  127, 0, -1, -1, 0, -1},

  // Some new sounds Tails 09-06-2002
  { "supert"  , false,  127, 0, -1, -1, 0, -1},
  { "lose\0\0", false,  127, 0, -1, -1, 0, -1},
  { "drown\0" , false,  127, 0, -1, -1, 0, -1},
  { "spkdth"  , false,  127, 0, -1, -1, 0, -1},

  // Player taunts/alternate msgs Tails 09-06-2002
  { "taunt1"   , false,  48, 0, 67, -1, 0, SKSPLTNT1},
  { "taunt2"   , false,  48, 0, 67, -1, 0, SKSPLTNT2},
  { "taunt3"   , false,  48, 0, 67, -1, 0, SKSPLTNT3},
  { "taunt4"   , false,  48, 0, 67, -1, 0, SKSPLTNT4},

  { "altow1"   , false,  48, 0, 67, -1, 0, SKSPLPAN1},
  { "altow2"   , false,  48, 0, 67, -1, 0, SKSPLPAN2},
  { "altow3"   , false,  48, 0, 67, -1, 0, SKSPLPAN3},
  { "altow4"   , false,  48, 0, 67, -1, 0, SKSPLPAN4},

  { "victr1"   , false,  48, 0, 67, -1, 0, SKSPLVCT1},
  { "victr2"   , false,  48, 0, 67, -1, 0, SKSPLVCT2},
  { "victr3"   , false,  48, 0, 67, -1, 0, SKSPLVCT3},
  { "victr4"   , false,  48, 0, 67, -1, 0, SKSPLVCT4},

  { "altdi1"   , false,  64, 0, 67, -1, 0, SKSPLDET1},
  { "altdi2"   , false,  64, 0, 67, -1, 0, SKSPLDET2},
  { "altdi3"   , false,  64, 0, 67, -1, 0, SKSPLDET3},
  { "altdi4"   , false,  64, 0, 67, -1, 0, SKSPLDET4},

  { "shldls"   , false,  64, 0, -1, -1, 0, -1},

  { "drill1"   , false,  64, 0, -1, -1, 0, -1},
  { "drill2"   , false,  64, 0, -1, -1, 0, -1},

  { "hoop1\0"   , false,  64, 0, -1, -1, 0, -1},
  { "hoop2\0"   , false,  64, 0, -1, -1, 0, -1},
  { "hoop3\0"   , false,  64, 0, -1, -1, 0, -1},
  { "ncitem"    , false,  64, 0, -1, -1, 0, -1},

  { "ideya\0"    , false,  127, 0, -1, -1, 0, -1},
  { "hidden"    , false,  64, 0, -1, -1, 0, -1},
  { "timeup"    , false,  64, 0, -1, -1, 0, -1},
  { "ngskid"    , false,  64, 0, -1, -1, 0, -1},
  { "prloop"    , false,  127, 0, -1, -1, 0, -1},
  { "nghurt"    , false, 127, 0, -1, -1, 0, -1},
  { "ngdone"    , true, 127, 0, -1, -1, 0, -1},

  { "pogo\0\0"    , false,  64, 0, -1, -1, 0, -1},
  { "gspray"    , false,  64, 0, -1, -1, 0, -1},
  { "ghit\0\0"    , false,  64, 0, -1, -1, 0, -1},

  { "alarm\0"    , false,  127, 0, -1, -1, 0, -1},

  { "fizzle"    , false,  127, 0, 67, -1, 0, -1},
  { "pop\0\0\0"    , false,  127, 0, 67, -1, 0, -1},

  { "trfire"    , true, 127, 0, 67, -1, 0, -1},
  { "turhit"    , false, 127, 0, 67, -1, 0, -1},
  { "trpowr"    , true, 127, 0, 67, -1, 0, -1},

  { "mario1" , false,  60, 0, -1, -1, 0, -1},
  { "mario2", false,  127, 0, -1, -1, 0, -1},
  { "mario3"   , false,  60, 0, -1, -1, 0, -1},
  { "mario4"   ,  true,  78, 0, -1, -1, 0, -1},
  { "mario5" , false,  78, 0, -1, -1, 0, -1},
  { "mario6" , false,  60, 0, -1, -1, 0, -1},
  { "mario7"   , false,  32, 0, -1, -1, 0, -1},
  { "mario8"   , false,  48, 0, 67, -1, 0, -1},
  { "mario9"   , true,  120, 0, -1, -1, 0, -1},
  { "marioa"   , true,  127, 0, -1, -1, 0, -1},
  { "thwomp"   , true,  127, 0, 67, -1, 0, -1},
  { "koopfr"   , true,  127, 0, 67, -1, 0, -1},

  { "ambint"   , true,  127, 0, 67, -1, 0, -1},
  { "sahitg" , false,  72, 0, -1, -1, 0, -1},
  { "spdpad" , false,  127, 0, -1, -1, 0, -1},

  { "ncspec"    , false,  64, 0, -1, -1, 0, -1}, // Tails 12-15-2003

  // skin sounds free slots to add sounds at run time (Boris HACK!!!)
  // initialized to NULL
};


// Prepare free sfx slots to add sfx at run time
void S_InitRuntimeSounds (void)
{
    int  i;

    for (i=sfx_freeslot0; i<=sfx_lastfreeslot; i++)
        S_sfx[i].name = NULL;
}

// Add a new sound fx into a free sfx slot.
//
int S_AddSoundFx (char *name,int singularity)
{
    int i;

    for(i=sfx_freeslot0;i<NUMSFX;i++)
    {
        if(!S_sfx[i].name)
        {
            S_sfx[i].name=(char *)Z_Malloc(7,PU_STATIC,NULL);
            strncpy(S_sfx[i].name,name,6);
            S_sfx[i].name[6]='\0';
            S_sfx[i].singularity=singularity;
            S_sfx[i].priority=60;
            S_sfx[i].link=0;
            S_sfx[i].pitch=-1;
            S_sfx[i].volume=-1;
            S_sfx[i].lumpnum=-1;
            S_sfx[i].skinsound=-1;
            S_sfx[i].usefulness=-1;

            // if precache load it here ! todo !
            S_sfx[i].data=0;
            return i;
        }
    }
    CONS_Printf("\2No more free sound slots\n");
    return 0;
}


void S_RemoveSoundFx (int id)
{
    if (id>=sfx_freeslot0 &&
        id<=sfx_lastfreeslot &&
        S_sfx[id].name)
    {
        Z_Free(S_sfx[id].name);
        S_sfx[id].name=NULL;
        S_sfx[id].lumpnum=-1;
        I_FreeSfx(&S_sfx[id]);
    }
}


//
// S_AddMusic
// Adds a single song to the runtime songs.
int S_AddMusic(char *name)
{
  int    i;
  char   lumpname[9];

  sprintf(lumpname, "d_%.6s", name);

  for(i = mus_firstfreeslot; i < mus_lastfreeslot; i++)
  {
    if(S_music[i].name == NULL)
    {
      S_music[i].name = Z_Strdup(name, PU_STATIC, 0);
      S_music[i].lumpnum = W_GetNumForName(lumpname);
      S_music[i].data = 0;
      return i;
    }
  }

  CONS_Printf("All music slots are full!\n");
  return 0;
}


int S_FindMusic(char *name)
{
  int   i;

  for(i = 0; i < NUMMUSIC; i++)
  {
    if(!S_music[i].name)
      continue;
    if(!stricmp(name, S_music[i].name)) return i;
  }

  return S_AddMusic(name);
}
