#
# Makefile.cfg for SRB2/Dreamcast
#

#include $(KOS_BASE)/Makefile.rules

#
#hmmm, the Dreamcast
#

ifdef ECHO
	CC=$(KOS_CC)
else
	CC=@$(KOS_CC)
endif

	NOHW = 1    #No working MiniGL right now
	NOHS = 1    #No HWSound right now
	NONET =1    #No LWIP
	i_net_o=$(OBJDIR)/i_udp.o #use KOS's UDP
	#NOMIXER = 1#Basic sound only
	NOIPX = 1   #No IPX network code

	OPTS = $(KOS_CFLAGS) -DLINUX -DDC -DNEEDALIGNED
ifndef NOHW
	OPTS := $(OPTS) -DMINI_GL_COMPATIBILITY -DKOS_GL_COMPATIBILITY
endif
	OPTS := -I$(KOS_BASE)/addons/include $(OPTS)
	LDFLAGS := $(KOS_LDFLAGS)
	LIBS := $(KOS_LIBS) -lconio
ifndef NOMIXER
	LIBS := -loggvorbisplay $(LIBS)
endif

ifndef NONET
	OPTS := $(OPTS) -I$(KOS_BASE)/../kos-ports/lwip/kos/include \
 -I$(KOS_BASE)/../kos-ports/lwip/lwip/src/include/ipv4 \
 -I$(KOS_BASE)/../kos-ports/lwip/lwip/src/include -DIPv4
	LDFLAGS := $(LDFLAGS) 
	LIBS := -llwip4 -lkosutils $(LIBS) 
endif
	
	i_system_o := $(i_system_o) $(OBJDIR)/dchelp.o
	i_main_o = $(KOS_START) $(OBJDIR)/i_main.o $(OBJEXTRA)

	# name of the exefile
	EXENAME=SRB2.elf
