#
# Makefile.cfg for SRB2/Dreamcast
#

#include $(KOS_BASE)/Makefile.rules

#
#hmmm, the Dreamcast
#

ifdef ECHO
	CC=$(KOS_CC)
else
	CC=@$(KOS_CC)
endif

	NOHW = 1    #No working MiniGL right now
	NOHS = 1    #No HWSound right now
	NOMIXER = 1 #Basic sound only
	NONET = 1   #No network code

	OPTS = $(KOS_CFLAGS) -DLINUX -DDC
ifndef NOHW
	OPTS = $(OPTS) -DMINI_GL_COMPATIBILITY -DKOS_GL_COMPATIBILITY
endif
	LDFLAGS := $(KOS_LDFLAGS)
	LIBS := $(KOS_LIBS) -lconio

	i_system_o := $(i_system_o) $(OBJDIR)/dchelp.o
	i_main_o = $(KOS_START) $(OBJDIR)/i_main.o $(OBJEXTRA)

	# name of the exefile
	EXENAME=SRB2.elf
