#
# Makefile.cfg for SRB2/XBOX
#

#
#hmmm, the XBOX
#

	NOHW = 1    #No working OpenGL right now
	NOHS = 1    #No HWSound right now
	NOASM = 1   #No Fast code
	NONET = 1   #No network code
	NOMD5 = 1   #No Slow MD5
	#SDLMAIN = 1 #SDLMain!

ifndef OPENXDK
	OPENXDK = /usr/local/openxdk
endif

ifdef ECHO
	CXBE = $(OPENXDK)/bin/cxbe
else
	CXBE = @$(OPENXDK)/bin/cxbe
endif
ifndef NOHW
	OPTS = $(OPTS) -DMINI_GL_COMPATIBILITY
endif

	BUILTLM = -fno-builtin
	OPTS := $(OPTS) -D_XBOX -std=gnu99 -ffreestanding -nostdlib $(BUILTLM) -fno-exceptions -mno-cygwin -march=i386 -I$(OPENXDK)/i386-pc-xbox/include -I$(OPENXDK)/include -I$(OPENXDK)/include/SDL
	LDFLAGS := $(LDFLAGS) -nostdlib -Wl,--file-alignment,0x20 -Wl,--section-alignment,0x20 -shared -Wl,--entry,_WinMainCRTStartup -Wl,--strip-all -L$(OPENXDK)/i386-pc-xbox/lib -L$(OPENXDK)/lib
	LIBS =  -lg -lc -lm -lSDL_Mixer -lSDL -lopenxdk -lhal -lc -lhal -lusb -lc -lxboxkrnl

	i_system_o := $(i_system_o) $(OBJDIR)/xboxhelp.o

	# name of the exefile
	EXENAME=SRB2XBOX.EXE
	BINNAME=default.xbe
