// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//-----------------------------------------------------------------------------
/// \file
/// \brief Sprite animation
///
/// Frame flags:
/// handles maximum brightness (torches, muzzle flare, light sources)

// we use the upper 16 bits of the frame field for effects.
#ifndef __P_PSPR__
#define __P_PSPR__

// Basic data types.
// Needs fixed point, and BAM angles.
#include "m_fixed.h"
#include "tables.h"

//
// Needs to include the precompiled
//  sprite animation tables.
// Header generated by multigen utility.
// This includes all the data for thing animation,
// i.e. the Thing Atrributes table
// and the Frame Sequence table.
#include "info.h"

#ifdef __GNUG__
#pragma interface
#endif

/// \brief Frame flags: only the frame number
#define FF_FRAMEMASK 0x7fff
/// \brief Frame flags: frame always appears full bright
#define FF_FULLBRIGHT 0x8000  // 
/// \brief Frame flags: 0 = no trans(opaque), 1-7 = transl. table
#define FF_TRANSMASK 0x70000  // 
/// \brief shift for FF_TRANSMASK
#define FF_TRANSSHIFT 16
/// \brief Frame flags: faB: new 'alpha' shade effect, for smoke..
#define FF_SMOKESHADE 0x80000  // sprite is an alpha channel

/**	\brief translucency tables

	\todo add another asm routine which use the fg and bg indexes in the
	inverse order so the 20-80 becomes 80-20 translucency, no need
	for other tables (thus 1090,2080,5050,8020,9010, and fire special)
*/
typedef enum
{
	tr_transmed = 1, /// sprite 50 backg 50  most shots
	tr_transmor = 2, ///       20       80  puffs
	tr_transhi  = 3, ///       10       90  blur effect
	tr_transfir = 4, /// 50 50 but brighter for fireballs, shots..
	tr_transfx1 = 5  /// 50 50 brighter some colors, else opaque for torches
} transnum_t;

#endif
