// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id: info.h,v 1.3 2000/04/04 00:32:46 stroggonmeth Exp $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Portions Copyright (C) 1998-2000 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// $Log: info.h,v $
// Revision 1.3  2000/04/04 00:32:46  stroggonmeth
// Initial Boom compatability plus few misc changes all around.
//
// Revision 1.2  2000/02/27 00:42:10  hurdler
// fix CR+LF problem
//
// Revision 1.1.1.1  2000/02/22 20:32:32  hurdler
// Initial import into CVS (v1.29 pr3)
//
//
// DESCRIPTION:
//      Thing frame/state LUT,
//      generated by multigen utilitiy.
//      This one is the original DOOM version, preserved.
//
//-----------------------------------------------------------------------------

#ifndef __INFO__
#define __INFO__

// Needed for action function pointer handling.
#include "d_think.h"

typedef enum
{
    SPR_SHTG,
    SPR_PUNG,
    SPR_PISG,
    SPR_PISF,
    SPR_SHTF,
    SPR_SHT2,
    SPR_CHGG,
    SPR_CHGF,
    SPR_MISG,
    SPR_MISF,
    SPR_SAWG,
    SPR_PLSG,
    SPR_PLSF,
    SPR_BFGG,
    SPR_BFGF,
    SPR_BLUD,
    SPR_PUFF,
    SPR_BAL1,
    SPR_BAL2,
    SPR_PLSS,
    SPR_PLSE,
    SPR_MISL,
    SPR_BFS1,
    SPR_BFE1,
    SPR_BFE2,
    SPR_TFOG,
    SPR_IFOG,
    SPR_PLAY,
    SPR_POSS,
    SPR_SPOS,
    SPR_FIRE,
    SPR_FATB,
    SPR_FBXP,
    SPR_MANF,
    SPR_BAL7,
    SPR_APLS,
    SPR_APBX,
    SPR_EGGM,
    SPR_BOSF,
    SPR_BEXP,
    SPR_FCAN,
    SPR_BON1,
    SPR_BKEY,
    SPR_RKEY,
    SPR_YKEY,
    SPR_BSKU,
    SPR_RSKU,
    SPR_YSKU,
    SPR_STIM,
    SPR_MEDI,
    SPR_EMMY, // emerald test tails
    SPR_PINV,
    SPR_CLIP,
    SPR_AMMO,
    SPR_ROCK,
    SPR_BROK,
    SPR_CELL,
    SPR_CELP,
    SPR_SHEL,
    SPR_SBOX,
    SPR_BPAK,
    SPR_BFUG,
    SPR_MGUN,
    SPR_CSAW,
    SPR_LAUN,
    SPR_PLAS,
    SPR_SHOT,
    SPR_SGN2,
    SPR_GRTV, // Tails 9-30-99
    SPR_SMT2,
    SPR_POL2,
    SPR_POL5,
    SPR_POL3,
    SPR_SHTV, // Tails 9-30-99
    SPR_POL6,
    SPR_GOR2,
    SPR_GOR3,
    SPR_GOR4,
    SPR_GOR5,
    SPR_SMIT,
    SPR_COL3,
    SPR_BUBL, // water bubble source Tails 03-07-2000
    SPR_BLTV, // Tails 9-30-99
    SPR_COL6,
    SPR_TRE2,
    SPR_YLTV, // Tails 9-30-99
    SPR_CEYE,
    SPR_FSKU,
    SPR_COL5,
    SPR_TGRN,
    SPR_TRED,
    SPR_SMBT,
    SPR_SMRT,
    SPR_HDB1,
    SPR_HDB2,
    SPR_HDB3,
    SPR_HDB4,
    SPR_HDB5,
    SPR_HDB6,
    SPR_POB1,
    SPR_POB2,
    SPR_TLMP,
    //Fab:
    SPR_SMOK,
    SPR_SPLA,
    SPR_TNT1, //SoM: 3/8/2000: add invisible sprite
	SPR_BIRD, // Tails 10-20-99 Birdie freed!
    SPR_SQRL, // Tails 10-20-99 Squirrel freed!
    SPR_BORB, // Tails 12-29-99 Blue Shield
    SPR_YORB, // Tails 12-29-99 Yellow Shield
    SPR_GORB, // Tails 12-29-99 Green Shield
    SPR_KORB, // Tails 12-29-99 Black Shield
    SPR_SPRK, // spark tails
    SPR_IVSP, // invincibility sparkles tails
    SPR_IVSQ, // finish invincibility sparkles tails
    SPR_DISS, // dissipating object tails
    SPR_BUBP, // Small bubble Tails 03-07-2000
    SPR_BUBO, // Medium bubble Tails 03-07-2000
    SPR_BUBN, // Large bubble Tails 03-07-2000
    SPR_BUBM, // Extra Large (would you like fries with that?) bubble Tails 03-07-2000
    SPR_CNTA, // Drowning Timer - 0 Tails 03-07-2000
    SPR_CNTB, // Drowning Timer - 1 Tails 03-07-2000
    SPR_CNTC, // Drowning Timer - 2 Tails 03-07-2000
    SPR_CNTD, // Drowning Timer - 3 Tails 03-07-2000
    SPR_CNTE, // Drowning Timer - 4 Tails 03-07-2000
    SPR_CNTF, // Drowning Timer - 5 Tails 03-07-2000
    SPR_POPP, // Extra Large bubble goes POP! Tails 03-08-2000
    SPR_PRUP, // 1up Box Tails 03-12-2000
    SPR_BKTV, // Black shield TV Tails 04-08-2000
    SPR_SCRA, // 100 score logo Tails 04-16-2000
    SPR_SCRB, // 200 score logo Tails 04-16-2000
    SPR_SCRC, // 500 score logo Tails 04-16-2000
    SPR_SCRD, // 1000 score logo Tails 04-16-2000
    SPR_SSPK, // Super Sonic Spark Tails 04-18-2000
    SPR_GRAS, // Grass debris Tails 05-14-2000
    SPR_YSPR, // Yellow Diagonal Spring Tails 05-17-2000
    SPR_WTRA, // Ambient Water Sound 1 Tails 06-10-2000
    SPR_WTRB, // Ambient Water Sound 2 Tails 06-10-2000
    SPR_WTRC, // Ambient Water Sound 3 Tails 06-10-2000
    SPR_WTRD, // Ambient Water Sound 4 Tails 06-10-2000
    SPR_WTRE, // Ambient Water Sound 5 Tails 06-10-2000
    SPR_WTRF, // Ambient Water Sound 6 Tails 06-10-2000
    SPR_WTRG, // Ambient Water Sound 7 Tails 06-10-2000
    SPR_WTRH, // Ambient Water Sound 8 Tails 06-10-2000
    SPR_SKIM, // Skim mine dropper Tails 06-13-2000
    SPR_MINE, // Skim mine Tails 06-13-2000
    SPR_FISH, // Greenflower Fish Tails 07-03-2000
    SPR_GARG, // Deep Sea Gargoyle Tails 07-29-2000
	SPR_SPLH, // Tails 12-08-2000
    SPR_GTHO, // Tails 12-05-99 Thok! mobj
    SPR_GRTH, // Tails 12-05-99 Thok! mobj
    SPR_PCTH, // Tails 12-05-99 Thok! mobj
    SPR_DRTH, // Tails 12-05-99 Thok! mobj
    SPR_STHO, // Tails 12-05-99 Thok! mobj
    SPR_OTHO, // Tails 12-05-99 Thok! mobj
    SPR_RTHO, // Tails 12-05-99 Thok! mobj
    SPR_BTHO, // Tails 12-05-99 Thok! mobj
    SPR_PTHO, // Tails 12-05-99 Thok! mobj
    SPR_DBTH, // Tails 12-05-99 Thok! mobj
    SPR_BGTH, // Tails 12-05-99 Thok! mobj
	SPR_THZP, // Techno Hill Zone Plant Tails 12-19-2000
	SPR_SIGN, // Level end sign Tails 01-14-2001
	SPR_RRNG, // Red Ring Tails 03-13-2001
	SPR_TTAG, // Tag Sign Tails 05-08-2001
	SPR_STEM, // Steam riser Tails 05-28-2001
	SPR_RFLG, // Red CTF Flag Tails 07-22-2001
	SPR_BFLG, // Blue CTF Flag Tails 07-22-2001
	SPR_GFLG, // Got Flag sign Tails 07-22-2001
	SPR_TOKE, // Special Stage Token Tails 08-11-2001
	SPR_CEMG, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMO, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMP, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMB, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMR, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEML, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_CEMY, // Chaos Emerald (intangible) Tails 08-18-2001
	SPR_JETB, // Jetty-Syn Bomber Tails 08-18-2001
	SPR_JETG, // Jetty-Syn Gunner Tails 08-25-2001
	SPR_JBUL, // Jetty-Syn Bullet Tails 08-25-2001
	SPR_MOUS, // Mouse Tails 08-26-2001
	SPR_DETN, // Deton Tails 08-26-2001
	SPR_XPLD, // Robot Explosion Tails 08-26-2001
	SPR_REDX, // RedXVI
	SPR_CHAN, // CEZ Chain Tails 11-02-2001
	SPR_CAPE, // Fake little Super Sonic cape Tails 11-12-2001
	SPR_SNO1, // Snowflake Tails 12-02-2001
	SPR_SANT, // Santa Tails 12-12-2001
	SPR_EMER, // Emerald Hunt 1 Tails 12-12-2001
	SPR_EMES, // Emerald Hunt 2 Tails 12-12-2001
	SPR_EMET, // Emerald Hunt 3 Tails 12-12-2001
	SPR_SBLL, // Snow Ball for Snow Buster Tails 12-12-2001
	SPR_SPIK, // Spike Ball Tails 12-18-2001
	SPR_CCOM, // Crawla Commander Tails 12-30-2001
    NUMSPRITES

} spritenum_t;

typedef enum
{
    S_NULL,
    S_LIGHTDONE,
    S_PUNCH,
    S_PUNCHDOWN,
    S_PUNCHUP,
    S_PUNCH1,
    S_PUNCH2,
    S_PUNCH3,
    S_PUNCH4,
    S_PUNCH5,
    S_PISTOL,
    S_PISTOLDOWN,
    S_PISTOLUP,
    S_PISTOL1,
    S_PISTOL2,
    S_PISTOL3,
    S_PISTOL4,
    S_PISTOLFLASH,
    S_SGUN,
    S_SGUNDOWN,
    S_SGUNUP,
    S_SGUN1,
    S_SGUN2,
    S_SGUN3,
    S_SGUN4,
    S_SGUN5,
    S_SGUN6,
    S_SGUN7,
    S_SGUN8,
    S_SGUN9,
    S_SGUNFLASH1,
    S_SGUNFLASH2,
    S_DSGUN,
    S_DSGUNDOWN,
    S_DSGUNUP,
    S_DSGUN1,
    S_DSGUN2,
    S_DSGUN3,
    S_DSGUN4,
    S_DSGUN5,
    S_DSGUN6,
    S_DSGUN7,
    S_DSGUN8,
    S_DSGUN9,
    S_DSGUN10,
    S_DSNR1,
    S_DSNR2,
    S_DSGUNFLASH1,
    S_DSGUNFLASH2,
    S_CHAIN,
    S_CHAINDOWN,
    S_CHAINUP,
    S_CHAIN1,
    S_CHAIN2,
    S_CHAIN3,
    S_CHAINFLASH1,
    S_CHAINFLASH2,
    S_MISSILE,
    S_MISSILEDOWN,
    S_MISSILEUP,
    S_MISSILE1,
    S_MISSILE2,
    S_MISSILE3,
    S_MISSILEFLASH1,
    S_MISSILEFLASH2,
    S_MISSILEFLASH3,
    S_MISSILEFLASH4,
    S_SAW,
    S_SAWB,
    S_SAWDOWN,
    S_SAWUP,
    S_SAW1,
    S_SAW2,
    S_SAW3,
    S_PLASMA,
    S_PLASMADOWN,
    S_PLASMAUP,
    S_PLASMA1,
    S_PLASMA2,
    S_PLASMAFLASH1,
    S_PLASMAFLASH2,
    S_BFG,
    S_BFGDOWN,
    S_BFGUP,
    S_BFG1,
    S_BFG2,
    S_BFG3,
    S_BFG4,
    S_BFGFLASH1,
    S_BFGFLASH2,
    S_BLOOD1,
    S_BLOOD2,
    S_BLOOD3,
    S_PUFF1,
    S_PUFF2,
    S_PUFF3,
    S_PUFF4,
    S_TBALL1,
    S_TBALL2,
    S_TBALLX1,
    S_TBALLX2,
    S_TBALLX3,
    S_RBALL1,
    S_RBALL2,
    S_RBALLX1,
    S_RBALLX2,
    S_RBALLX3,
    S_PLASBALL,
    S_PLASBALL2,
    S_PLASEXP,
    S_PLASEXP2,
    S_PLASEXP3,
    S_PLASEXP4,
    S_PLASEXP5,
    S_ROCKET,
    S_BFGSHOT,
    S_BFGSHOT2,
    S_BFGLAND,
    S_BFGLAND2,
    S_BFGLAND3,
    S_BFGLAND4,
    S_BFGLAND5,
    S_BFGLAND6,
    S_BFGEXP,
    S_BFGEXP2,
    S_BFGEXP3,
    S_BFGEXP4,
    S_EXPLODE1,
    S_EXPLODE2,
    S_EXPLODE3,
    S_TFOG,
    S_TFOG01,
    S_TFOG02,
    S_TFOG2,
    S_TFOG3,
    S_TFOG4,
    S_TFOG5,
    S_TFOG6,
    S_TFOG7,
    S_TFOG8,
    S_TFOG9,
    S_TFOG10,
    S_IFOG,
    S_IFOG01,
    S_IFOG02,
    S_IFOG2,
    S_IFOG3,
    S_IFOG4,
    S_IFOG5,
    S_PLAY,
    S_PLAY_TAP1, // Tails 12-03-99
    S_PLAY_TAP2, // Tails 12-03-99
    S_PLAY_RUN1,
    S_PLAY_RUN2,
    S_PLAY_RUN3,
    S_PLAY_RUN4,
    S_PLAY_RUN5, // Tails 9-14-99
    S_PLAY_RUN6, // Tails 9-14-99
    S_PLAY_RUN7, // Tails 9-14-99
    S_PLAY_RUN8, // Tails 9-14-99
    S_PLAY_ATK1, // Tails 9-14-99
    S_PLAY_ATK2, // Tails 9-14-99
    S_PLAY_ATK3, // Tails 9-14-99
    S_PLAY_ATK4, // Tails 9-14-99
    S_PLAY_PLG1, // Tails 9-14-99
    S_PLAY_SPD1, // Tails 03-02-2000
    S_PLAY_SPD2, // Tails 03-02-2000
    S_PLAY_SPD3, // Tails 03-02-2000
    S_PLAY_SPD4, // Tails 03-02-2000
    S_PLAY_ABL1, // Tails 03-02-2000
    S_PLAY_ABL2, // Tails 03-02-2000
    S_PLAY_SPC1, // Tails 03-02-2000
    S_PLAY_SPC2, // Tails 03-02-2000 ---- Finalized the character spec
    S_PLAY_SPC3, // Tails 03-02-2000
    S_PLAY_SPC4, // Tails 03-02-2000
	S_PLAY_CLIMB1, // Tails 01-03-2001
	S_PLAY_CLIMB2, // Tails 01-03-2001
	S_PLAY_CLIMB3, // Tails 01-03-2001
	S_PLAY_CLIMB4, // Tails 01-03-2001
	S_PLAY_CLIMB5, // Tails 01-03-2001
    S_PLAY_GASP, // Tails 03-02-2000
    S_PLAY_PAIN, // Tails 03-02-2000
    S_PLAY_DIE1, // Tails 03-02-2000
    S_PLAY_DIE2, // Tails 03-02-2000
    S_PLAY_DIE3, // Tails 03-02-2000
    S_PLAY_TEETER1, // Tails 03-02-2000
    S_PLAY_TEETER2, // Tails 03-02-2000
	S_PLAY_FALL1, // Tails 03-02-2000
	S_PLAY_FALL2, // Tails 03-02-2000
// New Crawla Animations Tails 06-13-2000
    S_POSS_STND,
    S_POSS_STND2,
    S_POSS_RUN1,
    S_POSS_RUN2,
    S_POSS_RUN3,
    S_POSS_RUN4,
    S_POSS_RUN5,
    S_POSS_RUN6,
    S_POSS_RUN7,
    S_POSS_RUN8,
    S_POSS_RUN9,
    S_POSS_RUN10,
    S_POSS_RUN11,
    S_POSS_RUN12,
    S_POSS_RUN13,
    S_POSS_RUN14,
    S_POSS_RUN15,
    S_POSS_RUN16,
    S_POSS_RUN17,
    S_POSS_DIE1,
    S_POSS_DIE2,
    S_POSS_DIE3,
    S_POSS_DIE4,
// XDIE frames deleted Tails 10-25-99
// New Crawla Animations Tails 06-13-2000
    S_SPOS_STND,
    S_SPOS_STND2,
    S_SPOS_RUN1,
    S_SPOS_RUN2,
    S_SPOS_RUN3,
    S_SPOS_RUN4,
    S_SPOS_RUN5,
    S_SPOS_RUN6,
    S_SPOS_RUN7,
    S_SPOS_RUN8,
    S_SPOS_RUN9,
    S_SPOS_RUN10,
    S_SPOS_RUN11,
    S_SPOS_RUN12,
    S_SPOS_RUN13,
    S_SPOS_RUN14,
    S_SPOS_RUN15,
    S_SPOS_RUN16,
    S_SPOS_RUN17,
    S_SPOS_DIE1,
    S_SPOS_DIE2,
    S_SPOS_DIE3,
    S_SPOS_DIE4,
// XDIE frames deleted Tails 10-25-99
    S_FIRE1,
    S_FIRE2,
    S_FIRE3,
    S_FIRE4,
    S_FIRE5,
    S_FIRE6,
    S_FIRE7,
    S_FIRE8,
    S_FIRE9,
    S_FIRE10,
    S_FIRE11,
    S_FIRE12,
    S_FIRE13,
    S_FIRE14,
    S_FIRE15,
    S_FIRE16,
    S_FIRE17,
    S_FIRE18,
    S_FIRE19,
    S_FIRE20,
    S_FIRE21,
    S_FIRE22,
    S_FIRE23,
    S_FIRE24,
    S_FIRE25,
    S_FIRE26,
    S_FIRE27,
    S_FIRE28,
    S_FIRE29,
    S_FIRE30,
    S_SMOKE1,
    S_SMOKE2,
    S_SMOKE3,
    S_SMOKE4,
    S_SMOKE5,
    S_TRACER,
    S_TRACER2,
    S_TRACEEXP1,
    S_TRACEEXP2,
    S_TRACEEXP3,
    S_FATSHOT1,
    S_FATSHOT2,
    S_FATSHOTX1,
    S_FATSHOTX2,
    S_FATSHOTX3,
    S_BRBALL1,
    S_BRBALL2,
    S_BRBALLX1,
    S_BRBALLX2,
    S_BRBALLX3,
    S_ARACH_PLAZ,
    S_ARACH_PLAZ2,
    S_ARACH_PLEX,
    S_ARACH_PLEX2,
    S_ARACH_PLEX3,
    S_ARACH_PLEX4,
    S_ARACH_PLEX5,
    S_EGGMOBILE_STND, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_STND2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_RUN4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_ATK2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_PAIN12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE1, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE2, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE3, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE4, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE5, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE6, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE7, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE8, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE9, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE10, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE11, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE12, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE13, // Boss 1 Tails 11-29-99
    S_EGGMOBILE_DIE14, // Boss 1 Tails 11-29-99
    S_SPAWN1,
    S_SPAWN2,
    S_SPAWN3,
    S_SPAWN4,
    S_SPAWNFIRE1,
    S_SPAWNFIRE2,
    S_SPAWNFIRE3,
    S_SPAWNFIRE4,
    S_SPAWNFIRE5,
    S_SPAWNFIRE6,
    S_SPAWNFIRE7,
    S_SPAWNFIRE8,
    S_BRAINEXPLODE1,
    S_BRAINEXPLODE2,
    S_BRAINEXPLODE3,
    S_BEXP,
    S_BEXP2,
    S_BEXP3,
    S_BEXP4,
    S_BEXP5,
    S_BBAR1,
    S_BBAR2,
    S_BBAR3,
    S_BBAR4, // Tails 10-31-99
    S_BBAR5, // Tails 10-31-99
    S_BBAR6, // Tails 10-31-99
    S_BBAR7, // Tails 10-31-99
    S_BON1,
    S_BON1A,
    S_BON1B,
    S_BON1C,
    S_BON1D,
    S_BON1E,
    S_BON1F, //Tails 9-15-99
    S_BON1G, //Tails 9-15-99
    S_BON1H, //Tails 9-15-99
    S_BON1I, //Tails 9-15-99
    S_BON1J, //Tails 9-15-99
    S_BON1K, //Tails 9-15-99
    S_BON1L, //Tails 9-15-99
    S_BON1M, //Tails 9-15-99
    S_BON1N, //Tails 9-15-99
    S_BON1O,  //Tails 9-15-99
    S_BON1P,  //Tails 10-29-99
    S_BON1Q,  //Tails 10-29-99
    S_BON1R,  //Tails 10-29-99
    S_BON1S,  //Tails 10-29-99
    S_BON1T,  //Tails 10-29-99
    S_BON1U,  //Tails 10-29-99
    S_BON1V,  //Tails 10-29-99
    S_BON1W,  //Tails 10-29-99
    S_BKEY,
    S_BKEY2,
    S_RKEY,
    S_RKEY2,
    S_YKEY,
    S_YKEY2,
    S_BSKULL,
    S_BSKULL2,
    S_RSKULL,
    S_RSKULL2,
    S_YSKULL,
    S_YSKULL2,
    S_STIM,
    S_STIM1, // Tails 9-30-99
    S_STIM2, // Tails 9-30-99
    S_STIM3, // Tails 9-30-99
    S_STIM4, // Tails 9-30-99
    S_STIM5, // Tails 9-30-99
    S_STIM6, // Tails 9-30-99
    S_STIM7, // Tails 9-30-99
    S_STIM8, // Tails 2-13-00
    S_MEDI,
    S_MEDI1, // Tails 9-30-99
    S_MEDI2, // Tails 9-30-99
    S_MEDI3, // Tails 9-30-99
    S_MEDI4, // Tails 9-30-99
    S_MEDI5, // Tails 9-30-99
    S_MEDI6, // Tails 9-30-99
    S_MEDI7, // Tails 9-30-99
    S_MEDI8, // Tails 2-13-00
    S_EMMY1, // start emerald tails
    S_EMMY2,
    S_EMMY3,
    S_EMMY4,
    S_EMMY5,
    S_EMMY6,
    S_EMMY7, // end emerald tails
    S_PINV, // start invincibility box tails
    S_PINV2,
    S_PINV3,
    S_PINV4,
    S_PINV5,
    S_PINV6,
    S_PINV7,
    S_PINV8,
    S_PINV9, // end invincibility box tails
    S_CLIP,
    S_AMMO,
    S_ROCK,
    S_BROK,
    S_CELL,
    S_CELP,
    S_SHEL,
    S_SBOX,
    S_BPAK,
    S_BFUG,
    S_MGUN,
    S_CSAW,
    S_LAUN,
    S_PLAS,
    S_SHOT,
    S_SHOT2,
    S_GRTV, // Tails 9-30-99
    S_GRTV1, // Tails 9-30-99
    S_GRTV2, // Tails 9-30-99
    S_GRTV3, // Tails 9-30-99
    S_GRTV4, // Tails 9-30-99
    S_GRTV5, // Tails 9-30-99
    S_GRTV6, // Tails 9-30-99
    S_GRTV7, // Tails 9-30-99
    S_GRTV8, // Tails 2-13-00
    S_STALAG,
    S_DEADTORSO,
    S_DEADBOTTOM,
    S_HEADSONSTICK,
    S_HEADSONSTICK2, // Tails 11-06-99
    S_HEADSONSTICK3, // Tails 11-06-99
    S_HEADSONSTICK4, // Tails 11-06-99
    S_HEADSONSTICK5, // Tails 11-06-99
    S_HEADSONSTICK6, // Tails 11-06-99
    S_HEADSONSTICK7, // Tails 11-06-99
    S_HEADSONSTICK8, // Tails 11-06-99
    S_GIBS,
    S_HEADCANDLES,
    S_HEADCANDLES2,
    S_SHTV, // Tails 9-30-99
    S_SHTV1, // Tails 9-30-99
    S_SHTV2, // Tails 9-30-99
    S_SHTV3, // Tails 9-30-99
    S_SHTV4, // Tails 9-30-99
    S_SHTV5, // Tails 9-30-99
    S_SHTV6, // Tails 9-30-99
    S_SHTV7, // Tails 9-30-99
    S_SHTV8, // Tails 2-13-00
    S_LIVESTICK,
    S_LIVESTICK2,
    S_MEAT2,
    S_MEAT3,
    S_MEAT4,
    S_MEAT5,
    S_STALAGTITE,
    S_TALLREDCOL, // It's da fan! Tails 12-05-99
    S_TALLREDCOL2, // It's da fan! Tails 12-05-99
    S_TALLREDCOL3, // It's da fan! Tails 12-05-99
    S_TALLREDCOL4, // It's da fan! Tails 12-05-99
    S_TALLREDCOL5, // It's da fan! Tails 12-05-99
    S_BUBBLES1, // Bubble Source Tails 03-07-2000
    S_BUBBLES2, // Bubble Source Tails 03-07-2000
    S_BLTV, // Tails 9-30-99
    S_BLTV1, // Tails 9-30-99
    S_BLTV2, // Tails 9-30-99
    S_BLTV3, // Tails 9-30-99
    S_BLTV4, // Tails 9-30-99
    S_BLTV5, // Tails 9-30-99
    S_BLTV6, // Tails 9-30-99
    S_BLTV7, // Tails 9-30-99
    S_BLTV8, // Tails 2-13-00
    S_SKULLCOL,
    S_BIGTREE,
    S_YLTV, // Tails 9-30-99
    S_YLTV1, // Tails 9-30-99
    S_YLTV2, // Tails 9-30-99
    S_YLTV3, // Tails 9-30-99
    S_YLTV4, // Tails 9-30-99
    S_YLTV5, // Tails 9-30-99
    S_YLTV6, // Tails 9-30-99
    S_YLTV7, // Tails 9-30-99
    S_YLTV8, // Tails 2-13-00
    S_EVILEYE,
    S_EVILEYE2,
    S_EVILEYE3,
    S_EVILEYE4,
    S_FLOATSKULL,
    S_FLOATSKULL2,
    S_FLOATSKULL3,
    S_HEARTCOL,
    S_HEARTCOL2,
    S_GREENTORCH,
    S_GREENTORCH2,
    S_GREENTORCH3,
    S_GREENTORCH4,
    S_REDTORCH,
    S_REDTORCH2,
    S_REDTORCH3,
    S_REDTORCH4,
    S_BTORCHSHRT,
    S_BTORCHSHRT2,
    S_BTORCHSHRT3,
    S_BTORCHSHRT4,
    S_RTORCHSHRT,
    S_RTORCHSHRT2,
    S_RTORCHSHRT3,
    S_RTORCHSHRT4,
    S_HANGNOGUTS,
    S_HANGBNOBRAIN,
    S_HANGTLOOKDN,
    S_HANGTSKULL,
    S_HANGTLOOKUP,
    S_HANGTNOBRAIN,
    S_COLONGIBS,
    S_COLONGIBS2, // Tails 11-07-99
    S_COLONGIBS3, // Tails 11-07-99
    S_COLONGIBS4, // Tails 11-07-99
    S_COLONGIBS5, // Tails 11-07-99
    S_COLONGIBS6, // Tails 11-07-99
    S_COLONGIBS7, // Tails 11-07-99
    S_COLONGIBS8, // Tails 11-07-99
    S_SMALLPOOL,
    S_TECHLAMP,
    S_TECHLAMP2,
    S_TECHLAMP3,
    S_TECHLAMP4,
    //Fab: added lava/slime damage burn smoke
    S_SMOK1,
    S_SMOK2,
    S_SMOK3,
    S_SMOK4,
    S_SMOK5,
    //Fab: added water splash
    S_SPLASH1,
    S_SPLASH2,
    S_SPLASH3,
    S_TNT1,   //SoM: 3/9/2000: add state for invisible sprite
	S_BIRD1, // Tails 10-20-99 Birdie free!
    S_BIRD2, // Tails 10-20-99 Birdie free!
    S_BIRD3, // Tails 10-23-99 Birdie free!
    S_SQRL1, // Tails 10-20-99 Squirrel free!
    S_SQRL2, // Tails 10-20-99 Squirrel free!
    S_SQRL3, // Tails 10-23-99 Squirrel free!
    S_SQRL4, // Tails 10-20-99 Squirrel free!
    S_SQRL5, // Tails 10-20-99 Squirrel free!
    S_SQRL6, // Tails 10-20-99 Squirrel free!
    S_SQRL7, // Tails 10-20-99 Squirrel free!
    S_SQRL8, // Tails 10-20-99 Squirrel free!
    S_SQRL9, // Tails 10-20-99 Squirrel free!
    S_SQRL10, // Tails 10-20-99 Squirrel free!
    S_BORB1, // Tails 12-29-99 shield mobjs
    S_BORB2, // Tails 12-29-99 shield mobjs
    S_BORB3, // Tails 12-29-99 shield mobjs
    S_BORB4, // Tails 12-29-99 shield mobjs
    S_BORB5, // Tails 12-29-99 shield mobjs
    S_BORB6, // Tails 12-29-99 shield mobjs
    S_BORB7, // Tails 12-29-99 shield mobjs
    S_BORB8, // Tails 12-29-99 shield mobjs
    S_YORB1, // Tails 12-29-99 shield mobjs
    S_YORB2, // Tails 12-29-99 shield mobjs
    S_YORB3, // Tails 12-29-99 shield mobjs
    S_YORB4, // Tails 12-29-99 shield mobjs
    S_YORB5, // Tails 12-29-99 shield mobjs
    S_YORB6, // Tails 12-29-99 shield mobjs
    S_YORB7, // Tails 12-29-99 shield mobjs
    S_YORB8, // Tails 12-29-99 shield mobjs
    S_GORB1, // Tails 12-29-99 shield mobjs
    S_GORB2, // Tails 06-28-2000 shield mobjs
    S_GORB3, // Tails 06-28-2000 shield mobjs
    S_GORB4, // Tails 06-28-2000 shield mobjs
    S_GORB5, // Tails 06-28-2000 shield mobjs
    S_GORB6, // Tails 06-28-2000 shield mobjs
    S_GORB7, // Tails 06-28-2000 shield mobjs
    S_GORB8, // Tails 06-28-2000 shield mobjs
    S_KORB1, // Tails 12-29-99 shield mobjs
    S_KORB2, // Tails 12-29-99 shield mobjs
    S_KORB3, // Tails 12-29-99 shield mobjs
    S_KORB4, // Tails 12-29-99 shield mobjs
    S_KORB5, // Tails 12-29-99 shield mobjs
    S_KORB6, // Tails 12-29-99 shield mobjs
    S_KORB7, // Tails 12-29-99 shield mobjs
    S_KORB8, // Tails 12-29-99 shield mobjs
    S_SPRK1, // spark start tails
    S_SPRK2,
    S_SPRK3,
    S_SPRK4,
    S_SPRK5, // spark
    S_SPRK6,
    S_SPRK7,
    S_SPRK8,
    S_SPRK9, // spark
    S_SPRK10,
    S_SPRK11,
    S_SPRK12,
    S_SPRK13, // spark
    S_SPRK14,
    S_SPRK15,
    S_SPRK16, // end spark tails
    S_IVSP1, // invincibility sparkles tails
    S_IVSP2, // invincibility sparkles tails
    S_IVSP3, // invincibility sparkles tails
    S_IVSP4, // invincibility sparkles tails
    S_IVSP5, // invincibility sparkles tails
    S_IVSP6, // invincibility sparkles tails
    S_IVSP7, // invincibility sparkles tails
    S_IVSP8, // invincibility sparkles tails
    S_IVSP9, // invincibility sparkles tails
    S_IVSP10, // invincibility sparkles tails
    S_IVSP11, // invincibility sparkles tails
    S_IVSP12, // invincibility sparkles tails
    S_IVSP13, // invincibility sparkles tails
    S_IVSP14, // invincibility sparkles tails
    S_IVSP15, // invincibility sparkles tails
    S_IVSP16, // invincibility sparkles tails
    S_IVSP17, // invincibility sparkles tails
    S_IVSP18, // invincibility sparkles tails
    S_IVSP19, // invincibility sparkles tails
    S_IVSP20, // invincibility sparkles tails
    S_IVSP21, // invincibility sparkles tails
    S_IVSP22, // invincibility sparkles tails
    S_IVSP23, // invincibility sparkles tails
    S_IVSP24, // invincibility sparkles tails
    S_IVSP25, // invincibility sparkles tails
    S_IVSP26, // invincibility sparkles tails
    S_IVSP27, // invincibility sparkles tails
    S_IVSP28, // invincibility sparkles tails
    S_IVSP29, // invincibility sparkles tails
    S_IVSQ1, // invincibility sparkles finish tails
    S_IVSQ2, // invincibility sparkles finish tails
    S_IVSQ3, // invincibility sparkles finish tails
    S_DISS, // dissipating object tails
    S_SMALLBUBBLE, // small bubble Tails 03-07-2000
    S_SMALLBUBBLE1, // small bubble Tails 03-07-2000
    S_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
    S_MEDIUMBUBBLE1, // medium bubble Tails 03-07-2000
    S_LARGEBUBBLE, // large bubble Tails 03-07-2000
    S_EXTRALARGEBUBBLE, // extra large bubble (breathable) Tails 03-07-2000
    S_EXTRALARGEBUBBLE1, // extra large bubble (breathable) Tails 03-07-2000
    S_ZERO1, // Drowning Timer - 0 Tails 03-07-2000
    S_ONE1, // Drowning Timer - 1 Tails 03-07-2000
    S_TWO1, // Drowning Timer - 2 Tails 03-07-2000
    S_THREE1, // Drowning Timer - 3 Tails 03-07-2000
    S_FOUR1, // Drowning Timer - 4 Tails 03-07-2000
    S_FIVE1, // Drowning Timer - 5 Tails 03-07-2000
    S_POP1, // Extra Large bubble goes POP! Tails 03-08-2000
    S_PRUP1, // 1Up box Tails 03-12-2000
    S_PRUP2, // 1Up box Tails 03-12-2000
    S_PRUP3, // 1Up box Tails 03-12-2000
    S_PRUP4, // 1Up box Tails 03-12-2000
    S_PRUP5, // 1Up box Tails 03-12-2000
    S_PRUP6, // 1Up box Tails 03-12-2000
    S_PRUP7, // 1Up box Tails 03-12-2000
    S_PRUP8, // 1Up box Tails 03-12-2000
    S_PRUP9, // 1Up box Tails 03-12-2000
    S_BKTV1, // Black shield TV Tails 04-08-2000
    S_BKTV2, // Black shield TV Tails 04-08-2000
    S_BKTV3, // Black shield TV Tails 04-08-2000
    S_BKTV4, // Black shield TV Tails 04-08-2000
    S_BKTV5, // Black shield TV Tails 04-08-2000
    S_BKTV6, // Black shield TV Tails 04-08-2000
    S_BKTV7, // Black shield TV Tails 04-08-2000
    S_BKTV8, // Black shield TV Tails 04-08-2000
    S_BKTV9, // Black shield TV Tails 04-08-2000
    S_SCRA, // 100 score logo Tails 04-16-2000
    S_SCRA2, // 100 score logo Tails 04-16-2000
    S_SCRB, // 200 score logo Tails 04-16-2000
    S_SCRB2, // 200 score logo Tails 04-16-2000
    S_SCRC, // 500 score logo Tails 04-16-2000
    S_SCRC2, // 500 score logo Tails 04-16-2000
    S_SCRD, // 1000 score logo Tails 04-16-2000
    S_SCRD2, // 1000 score logo Tails 04-16-2000
    S_SSPK1, // Super Sonic Spark Tails 04-18-2000
    S_SSPK2, // Super Sonic Spark Tails 04-18-2000
    S_SSPK3, // Super Sonic Spark Tails 04-18-2000
    S_SSPK4, // Super Sonic Spark Tails 04-18-2000
    S_SSPK5, // Super Sonic Spark Tails 04-18-2000
    S_GRASS1, // Grass debris Tails 05-14-2000
    S_GRASS2, // Grass debris Tails 05-14-2000
    S_GRASS3, // Grass debris Tails 05-14-2000
    S_GRASS4, // Grass debris Tails 05-14-2000
    S_GRASS5, // Grass debris Tails 05-14-2000
    S_GRASS6, // Grass debris Tails 05-14-2000
    S_GRASS7, // Grass debris Tails 05-14-2000
    S_YDIAG1, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG2, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG3, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG4, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG5, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG6, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG7, // Yellow Diagonal Spring Tails 05-17-2000
    S_YDIAG8, // Yellow Diagonal Spring Tails 05-17-2000
    S_AWATERA1, // Ambient Water Sound 1 Tails 06-10-2000
    S_AWATERA2, // Ambient Water Sound 1 Tails 06-10-2000
    S_AWATERB1, // Ambient Water Sound 2 Tails 06-10-2000
    S_AWATERB2, // Ambient Water Sound 2 Tails 06-10-2000
    S_AWATERC1, // Ambient Water Sound 3 Tails 06-10-2000
    S_AWATERC2, // Ambient Water Sound 3 Tails 06-10-2000
    S_AWATERD1, // Ambient Water Sound 4 Tails 06-10-2000
    S_AWATERD2, // Ambient Water Sound 4 Tails 06-10-2000
    S_AWATERE1, // Ambient Water Sound 5 Tails 06-10-2000
    S_AWATERE2, // Ambient Water Sound 5 Tails 06-10-2000
    S_AWATERF1, // Ambient Water Sound 6 Tails 06-10-2000
    S_AWATERF2, // Ambient Water Sound 6 Tails 06-10-2000
    S_AWATERG1, // Ambient Water Sound 7 Tails 06-10-2000
    S_AWATERG2, // Ambient Water Sound 7 Tails 06-10-2000
    S_AWATERH1, // Ambient Water Sound 8 Tails 06-10-2000
    S_AWATERH2, // Ambient Water Sound 8 Tails 06-10-2000
    S_SKIM1, // Skim mine dropper Tails 06-13-2000
    S_SKIM2, // Skim mine dropper Tails 06-13-2000
    S_SKIM3, // Skim mine dropper Tails 06-13-2000
    S_SKIM4, // Skim mine dropper Tails 06-13-2000
    S_SKIM5, // Skim mine dropper Tails 06-13-2000
    S_SKIM6, // Skim mine dropper Tails 06-13-2000
    S_SKIM7, // Skim mine dropper Tails 06-13-2000
    S_SKIM8, // Skim mine dropper Tails 06-13-2000
    S_SKIM9, // Skim mine dropper Tails 06-13-2000
    S_SKIM10, // Skim mine dropper Tails 06-13-2000
    S_SKIM11, // Skim mine dropper Tails 06-13-2000
    S_SKIM12, // Skim mine dropper Tails 06-13-2000
    S_SKIM13, // Skim mine dropper Tails 06-13-2000
    S_SKIM14, // Skim mine dropper Tails 06-13-2000
    S_SKIM15, // Skim mine dropper Tails 06-13-2000
    S_SKIM16, // Skim mine dropper Tails 06-13-2000
    S_SKIM17, // Skim mine dropper Tails 06-13-2000
    S_SKIM18, // Skim mine dropper Tails 06-13-2000
    S_SKIM19, // Skim mine dropper Tails 06-13-2000
    S_SKIM20, // Skim mine dropper Tails 06-13-2000
    S_SKIM21, // Skim mine dropper Tails 06-13-2000
    S_SKIM22, // Skim mine dropper Tails 06-13-2000
    S_SKIM23, // Skim mine dropper Tails 06-13-2000
    S_SKIM24, // Skim mine dropper Tails 06-13-2000
    S_SKIM25, // Skim mine dropper Tails 06-13-2000
    S_SKIM26, // Skim mine dropper Tails 06-13-2000
    S_SKIM27, // Skim mine dropper Tails 06-13-2000
    S_SKIM28, // Skim mine dropper Tails 06-13-2000
    S_SKIM29, // Skim mine dropper Tails 06-13-2000
    S_SKIM30, // Skim mine dropper Tails 06-13-2000
    S_SKIM_BOOM1, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM2, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM3, // Skim mine dropper explode Tails 06-13-2000
    S_SKIM_BOOM4, // Skim mine dropper explode Tails 06-13-2000
    S_MINE1, // Skim mine Tails 06-13-2000
    S_MINE_BOOM1, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM2, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM3, // Skim mine explode Tails 06-13-2000
    S_MINE_BOOM4, // Skim mine explode Tails 06-13-2000
    S_FISH1, // Greenflower Fish Tails 07-03-2000
    S_FISH2, // Greenflower Fish Tails 07-03-2000
    S_FISH3, // Greenflower Fish Tails 07-03-2000
    S_FISH4, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE1, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE2, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE3, // Greenflower Fish Tails 07-03-2000
    S_FISH_DIE4, // Greenflower Fish Tails 07-03-2000
    S_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	S_SPLISH1, // Tails 12-08-2000
	S_SPLISH2, // Tails 12-08-2000
	S_SPLISH3, // Tails 12-08-2000
	S_SPLISH4, // Tails 12-08-2000
	S_SPLISH5, // Tails 12-08-2000
	S_SPLISH6, // Tails 12-08-2000
	S_SPLISH7, // Tails 12-08-2000
	S_SPLISH8, // Tails 12-08-2000
	S_SPLISH9, // Tails 12-08-2000
    S_GTHOK1, // Tails 12-05-99 Thok! mobj
    S_GRTHOK1, // Tails 12-05-99 Thok! mobj
    S_PCTHOK1, // Tails 12-05-99 Thok! mobj
    S_DRTHOK1, // Tails 12-05-99 Thok! mobj
    S_STHOK1, // Tails 12-05-99 Thok! mobj
    S_OTHOK1, // Tails 12-05-99 Thok! mobj
    S_RTHOK1, // Tails 12-05-99 Thok! mobj
    S_BTHOK1, // Tails 12-05-99 Thok! mobj
    S_PTHOK1, // Tails 12-05-99 Thok! mobj
    S_DBTHOK1, // Tails 12-05-99 Thok! mobj
    S_BGTHOK1, // Tails 12-05-99 Thok! mobj
	S_THZPLANT1, // THZ Plant Tails 12-19-2000
	S_THZPLANT2, // THZ Plant Tails 12-19-2000
	S_THZPLANT3, // THZ Plant Tails 12-19-2000
	S_THZPLANT4, // THZ Plant Tails 12-19-2000
	S_SIGN1, // Level end sign Tails 01-14-2001
	S_SIGN2, // Level end sign Tails 01-14-2001
	S_SIGN3, // Level end sign Tails 01-14-2001
	S_SIGN4, // Level end sign Tails 01-14-2001
	S_SIGN5, // Level end sign Tails 01-14-2001
	S_SIGN6, // Level end sign Tails 01-14-2001
	S_SIGN7, // Level end sign Tails 01-14-2001
	S_SIGN8, // Level end sign Tails 01-14-2001
	S_SIGN9, // Level end sign Tails 01-14-2001
	S_SIGN10, // Level end sign Tails 01-14-2001
	S_SIGN11, // Level end sign Tails 01-14-2001
	S_SIGN12, // Level end sign Tails 01-14-2001
	S_SIGN13, // Level end sign Tails 01-14-2001
	S_SIGN14, // Level end sign Tails 01-14-2001
	S_SIGN15, // Level end sign Tails 01-14-2001
	S_SIGN16, // Level end sign Tails 01-14-2001
	S_SIGN17, // Level end sign Tails 01-14-2001
	S_SIGN18, // Level end sign Tails 01-14-2001
	S_SIGN19, // Level end sign Tails 01-14-2001
	S_SIGN20, // Level end sign Tails 01-14-2001
	S_SIGN21, // Level end sign Tails 01-14-2001
	S_SIGN22, // Level end sign Tails 01-14-2001
	S_SIGN23, // Level end sign Tails 01-14-2001
	S_SIGN24, // Level end sign Tails 01-14-2001
	S_SIGN25, // Level end sign Tails 01-14-2001
	S_SIGN26, // Level end sign Tails 01-14-2001
	S_SIGN27, // Level end sign Tails 01-14-2001
	S_SIGN28, // Level end sign Tails 01-14-2001
	S_SIGN29, // Level end sign Tails 01-14-2001
	S_SIGN30, // Level end sign Tails 01-14-2001
	S_SIGN31, // Level end sign Tails 01-14-2001
	S_SIGN32, // Level end sign Tails 01-14-2001
	S_SIGN33, // Level end sign Tails 01-14-2001
	S_SIGN34, // Level end sign Tails 01-14-2001
	S_SIGN35, // Level end sign Tails 01-14-2001
	S_SIGN36, // Level end sign Tails 01-14-2001
	S_SIGN37, // Level end sign Tails 01-14-2001
	S_SIGN38, // Level end sign Tails 01-14-2001
	S_SIGN39, // Level end sign Tails 01-14-2001
	S_SIGN40, // Level end sign Tails 01-14-2001
	S_SIGN41, // Level end sign Tails 01-14-2001
	S_SIGN42, // Level end sign Tails 01-14-2001
	S_SIGN43, // Level end sign Tails 01-14-2001
	S_SIGN44, // Level end sign Tails 01-14-2001
	S_SIGN45, // Level end sign Tails 01-14-2001
	S_SIGN46, // Level end sign Tails 01-14-2001
	S_SIGN47, // Level end sign Tails 01-14-2001
	S_SIGN48, // Level end sign Tails 01-14-2001
	S_SIGN49, // Level end sign Tails 01-14-2001
	S_SIGN50, // Level end sign Tails 01-14-2001
	S_SIGN51, // Level end sign Tails 01-14-2001
	S_SIGN52, // Level end sign Tails 01-14-2001
	S_RRNG1, // Tails 03-13-2001
	S_RRNG2, // Tails 03-13-2001
	S_RRNG3, // Tails 03-13-2001
	S_RRNG4, // Tails 03-13-2001
	S_RRNG5, // Tails 03-13-2001
	S_RRNG6, // Tails 03-13-2001
	S_RRNG7, // Tails 03-13-2001
	S_RRNG8, // Tails 03-13-2001
	S_TTAG1, // Tails 05-08-2001
	S_STEAM1, // Steam riser Tails 05-28-2001
	S_STEAM2, // Steam riser Tails 05-28-2001
	S_STEAM3, // Steam riser Tails 05-28-2001
	S_STEAM4, // Steam riser Tails 05-28-2001
	S_STEAM5, // Steam riser Tails 05-28-2001
	S_STEAM6, // Steam riser Tails 05-28-2001
	S_STEAM7, // Steam riser Tails 05-28-2001
	S_STEAM8, // Steam riser Tails 05-28-2001
	S_REDFLAG, // Red CTF Flag Tails 07-22-2001
	S_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	S_GOTFLAG1, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG2, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG3, // Got Flag sign Tails 07-22-2001
	S_GOTFLAG4, // Got Flag sign Tails 07-22-2001
	S_TOKEN, // Special Stage Token Tails 08-11-2001
	S_TOKEN2, // Special Stage Token Tails 08-17-2001
	S_CEMG, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMO, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMP, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMB, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMR, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEML, // Chaos Emerald (intangible) Tails 08-18-2001
	S_CEMY, // Chaos Emerald (intangible) Tails 08-18-2001
	S_JETBLOOK1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBLOOK2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBZOOM2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE1, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE2, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE3, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETBDIE4, // Jetty-Syn Bomber Tails 08-18-2001
	S_JETGLOOK1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGLOOK2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGZOOM2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGSHOOT2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE1, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE2, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE3, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETGDIE4, // Jetty-Syn Gunner Tails 08-25-2001
	S_JETBULLET1, // Jetty-Syn Bullet Tails 08-25-2001
	S_JETBULLET2, // Jetty-Syn Bullet Tails 08-25-2001
	S_MOUSE1, // Mouse Tails 08-26-2001
	S_MOUSE2, // Mouse Tails 08-26-2001
	S_DETON1, // Deton Tails 08-26-2001
	S_DETON2, // Deton Tails 08-26-2001
	S_XPLD1, // Robot Explosion Tails 08-26-2001
	S_XPLD2, // Robot Explosion Tails 08-26-2001
	S_XPLD3, // Robot Explosion Tails 08-26-2001
	S_XPLD4, // Robot Explosion Tails 08-26-2001
	S_REDVXI, // RedXVI
	S_CEZCHAIN, // CEZ Chain Tails 11-02-2001
	S_CAPE1, // Fake little Super Sonic cape Tails 11-12-2001
	S_CAPE2, // Fake little Super Sonic cape Tails 11-12-2001
	S_SNOW1, // Snowflake Tails 12-02-2001
	S_SNOW2, // Snowflake Tails 12-02-2001
	S_SNOW3, // Snowflake Tails 12-02-2001
	S_SANTA1, // Santa Tails 12-12-2001
	S_EMER1, // Emerald Hunt 1 Tails 12-12-2001
	S_EMES1, // Emerald Hunt 2 Tails 12-12-2001
	S_EMET1, // Emerald Hunt 3 Tails 12-12-2001
	S_SBLL1, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SBLL2, // Snow Ball for Snow Buster Tails 12-12-2001
	S_SPIKEBALL1, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL2, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL3, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL4, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL5, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL6, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL7, // Spike Ball Tails 12-18-2001
	S_SPIKEBALL8, // Spike Ball Tails 12-18-2001
	S_CCOMMAND1, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND2, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND3, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND4, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND5, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND6, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND7, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND8, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND9, // Crawla Commander Tails 12-30-2001
	S_CCOMMAND10, // Crawla Commander Tails 12-30-2001

    NUMSTATES
} statenum_t;


typedef struct
{
  spritenum_t   sprite;
  long          frame;          //faB: we use the upper 16bits for translucency
                                //     and other shade effects
  long          tics;
  // void       (*action) ();
  actionf_t     action;
  statenum_t    nextstate;
//  long          misc1, misc2;
} state_t;


extern state_t  states[NUMSTATES];
extern char *sprnames[NUMSPRITES+1];



typedef enum {
    MT_PLAYER,
    MT_BLUECRAWLA,
    MT_REDCRAWLA,
    MT_FIRE,
    MT_TRACER,
    MT_SMOKE,
    MT_FATSHOT,
    MT_BRUISERSHOT,
    MT_EGGMOBILE,
    MT_SPAWNSHOT,
    MT_SPAWNFIRE,
    MT_TROOPSHOT,
    MT_HEADSHOT,
    MT_ROCKET,
    MT_PLASMA,
    MT_BFG,
    MT_ARACHPLAZ,
    MT_PUFF,
    MT_BLOOD,
    MT_TFOG,
    MT_IFOG,
    MT_TELEPORTMAN,
    MT_EXTRABFG,
    MT_MISC2,
    MT_MISC4,
    MT_MISC5,
    MT_MISC6,
    MT_MISC7,
    MT_MISC8,
    MT_MISC9,
    MT_MISC10,
    MT_MISC11,
    MT_EMMY, // emerald tails
    MT_INV,
    MT_CLIP,
    MT_MISC17,
    MT_MISC18,
    MT_MISC19,
    MT_MISC20,
    MT_MISC21,
    MT_MISC22,
    MT_MISC23,
    MT_MISC24,
    MT_BFG9000,
    MT_CHAINGUN,
    MT_SHAINSAW,
    MT_ROCKETLAUNCH,
    MT_PLASMAGUN,
    MT_SHOTGUN,
    MT_SUPERSHOTGUN,
    MT_MISC29,
    MT_MISC31,
    MT_MISC34,
    MT_BUBBLES, // Bubble source Tails 03-07-2000
    MT_MISC36,
    MT_MISC37,
    MT_MISC38,
    MT_MISC39,
    MT_MISC42,
    MT_MISC43,
    MT_MISC44,
    MT_MISC46,
    MT_MISC47,
    MT_MISC48,
    MT_MISC50,
    MT_MISC52,
    MT_MISC53,
    MT_MISC54,
    MT_MISC55,
    MT_MISC56,
    MT_MISC57,
    MT_MISC58,
    MT_MISC59,
    MT_MISC62,
    MT_MISC63,
    MT_MISC67,
    MT_MISC68,
    MT_MISC69,
    MT_MISC70,
    MT_MISC71,
    MT_MISC73,
    MT_MISC74,
    MT_MISC75,
    MT_MISC76,
    MT_MISC77,
    MT_MISC78,
    MT_MISC79,
    MT_MISC80,
    MT_MISC81,
    MT_MISC82,
    MT_MISC83,
    MT_MISC84,
    MT_MISC85,
    MT_CHASECAM,
    MT_SPIRIT,
    MT_SMOK,        // test lave/slime damage smoke
    MT_SPLASH,      // test water splash
    MT_PUSH,    //SoM: 3/8/2000: controls push source
    MT_PULL,    //SoM: 3/8/2000: controls pull source
	MT_FLINGRING,   //SOM: Test rings flying
    MT_BIRD, // Tails 10-20-99 Birdie freed!
    MT_SQRL, // Tails 10-20-99 Squirrel freed!
    MT_BLUEORB, // Tails 12-29-99 shield mobjs
    MT_YELLOWORB, // Tails 12-29-99 shield mobjs
    MT_GREENORB, // Tails 12-29-99 shield mobjs
    MT_BLACKORB, // Tails 12-29-99 shield mobjs
    MT_SPARK, //spark tails
    MT_IVSP, // invincibility sparkles tails
    MT_IVSQ, // invincibility sparkles finish tails
    MT_DISS, // dissipating object tails
    MT_SMALLBUBBLE, // small bubble Tails 03-07-2000
    MT_MEDIUMBUBBLE, // medium bubble Tails 03-07-2000
//    MT_LARGEBUBBLE, // large bubble Tails 03-07-2000
    MT_EXTRALARGEBUBBLE, // extra large bubble Tails 03-07-2000
    MT_ZERO, // Drowning Timer - 0 Tails 03-07-2000
    MT_ONE, // Drowning Timer - 1 Tails 03-07-2000
    MT_TWO, // Drowning Timer - 2 Tails 03-07-2000
    MT_THREE, // Drowning Timer - 3 Tails 03-07-2000
    MT_FOUR, // Drowning Timer - 4 Tails 03-07-2000
    MT_FIVE, // Drowning Timer - 5 Tails 03-07-2000
    MT_POP, // Extra Large bubble goes POP! Tails 03-08-2000
    MT_PRUP, // 1up Box Tails 03-12-2000
    MT_BKTV, // Black shield TV Tails 04-08-2000
    MT_SCRA, // 100 score logo Tails 04-16-2000
    MT_SCRB, // 200 score logo Tails 04-16-2000
    MT_SCRC, // 500 score logo Tails 04-16-2000
    MT_SCRD, // 1000 score logo Tails 04-16-2000
    MT_SUPERSPARK, // Super Sonic Spark Tails 04-18-2000
    MT_GRASSDEBRIS, // Grass debris Tails 05-14-2000
    MT_YELLOWDIAG, // Yellow Diagonal Spring Tails 05-17-2000
    MT_AWATERA, // Ambient Water Sound 1 Tails 06-10-2000
    MT_AWATERB, // Ambient Water Sound 2 Tails 06-10-2000
    MT_AWATERC, // Ambient Water Sound 3 Tails 06-10-2000
    MT_AWATERD, // Ambient Water Sound 4 Tails 06-10-2000
    MT_AWATERE, // Ambient Water Sound 5 Tails 06-10-2000
    MT_AWATERF, // Ambient Water Sound 6 Tails 06-10-2000
    MT_AWATERG, // Ambient Water Sound 7 Tails 06-10-2000
    MT_AWATERH, // Ambient Water Sound 8 Tails 06-10-2000
    MT_SKIM, // Skim mine dropper Tails 06-13-2000
    MT_MINE, // Skim mine Tails 06-13-2000
    MT_GFZFISH, // Greenflower Fish Tails 07-03-2000
    MT_GARGOYLE, // Deep Sea Gargoyle Tails 07-29-2000
	MT_SPEEDPAD, // "speed pad" Tails 12-01-2000
	MT_SPLISH, // Water splish! Tails 12-08-2000
    MT_GTHOK, // Tails 12-05-99 Thok! mobj
    MT_GRTHOK, // Tails 12-05-99 Thok! mobj
    MT_PCTHOK, // Tails 12-05-99 Thok! mobj
    MT_DRTHOK, // Tails 12-05-99 Thok! mobj
    MT_STHOK, // Tails 12-05-99 Thok! mobj
    MT_OTHOK, // Tails 12-05-99 Thok! mobj
    MT_RTHOK, // Tails 12-05-99 Thok! mobj
    MT_BTHOK, // Tails 12-05-99 Thok! mobj
    MT_PTHOK, // Tails 12-05-99 Thok! mobj
    MT_DBTHOK, // Tails 12-05-99 Thok! mobj
    MT_BGTHOK, // Tails 12-05-99 Thok! mobj
	MT_THZPLANT, // THZ Plant Tails 12-19-2000
	MT_SIGN, // Level end sign Tails 01-14-2001
	MT_REDRING, // Tails 03-13-2001
	MT_TAG, // Tag Sign Tails 05-08-2001
	MT_STEAM, // Steam riser Tails 05-28-2001
	MT_REDFLAG, // Red CTF Flag Tails 07-22-2001
	MT_BLUEFLAG, // Blue CTF Flag Tails 07-22-2001
	MT_GOTFLAG, // Got Flag sign Tails 07-22-2001
	MT_GOTFLAG2, // Got Flag sign Tails 08-02-2001
	MT_TOKEN, // Special Stage Token Tails 08-11-2001
	MT_GREENEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_ORANGEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_PINKEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_BLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_REDEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_LIGHTBLUEEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_GREYEMERALD, // Chaos Emerald (intangible) Tails 08-18-2001
	MT_JETTBOMBER, // Jetty-Syn Bomber Tails 08-18-2001
	MT_JETTGUNNER, // Jetty-Syn Gunner Tails 08-25-2001
	MT_JETTBULLET, // Jetty-Syn Bullet Tails 08-25-2001
	MT_MOUSE, // Mouse Tails 08-26-2001
	MT_DETON, // Deton Tails 08-26-2001
	MT_EXPLODE, // Robot Explosion Tails 08-26-2001
	MT_REDVXI, // RedVXI
	MT_CHAIN, // CEZ Chain Tails 11-02-2001
	MT_CAPE, // Fake little Super Sonic cape Tails 11-12-2001
	MT_SNOWFLAKE, // Snowflake Tails 12-02-2001
	MT_SANTA, // Santa Tails 12-12-2001
	MT_EMERHUNT, // Emerald Hunt 1 Tails 12-12-2001
	MT_EMESHUNT, // Emerald Hunt 2 Tails 12-12-2001
	MT_EMETHUNT, // Emerald Hunt 3 Tails 12-12-2001
	MT_SNOWBALL, // Snow Ball for Snow Buster Tails 12-12-2001
	MT_SPIKEBALL, // Spike Ball Tails 12-18-2001
	MT_CRAWLACOMMANDER, // Crawla Commander Tails 12-30-2001
    NUMMOBJTYPES

} mobjtype_t;

typedef struct
{
    int doomednum;
    int spawnstate;
    int spawnhealth;
    int seestate;
    int seesound;
    int reactiontime;
    int attacksound;
    int painstate;
    int painchance;
    int painsound;
    int meleestate;
    int missilestate;
    int deathstate;
    int xdeathstate;
    int deathsound;
    int speed;
    int radius;
    int height;
    int mass;
    int damage;
    int activesound;
    int flags;
    int raisestate;
} mobjinfo_t;

extern mobjinfo_t mobjinfo[NUMMOBJTYPES];

#endif
